# Generated by Django 3.1.12 on 2021-08-03 20:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_blocklist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="birth_year",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="company",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="company_size",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="highest_education",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="job_function",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="job_title",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="leadership_level",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="years_experience",
        ),
    ]
