# Generated by Django 3.2.13 on 2022-06-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normalized_username',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
