# Generated by Django 3.2.15 on 2023-01-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
