# Generated by Django 3.2.13 on 2022-06-14 20:27

from django.db import migrations, transaction
from users.models import User


def update_normalized_username_field(apps, schema_editor):
    with transaction.atomic():
        for user in User.objects.all():
            user.make_normalized_username()

            if (
                User.objects.filter(
                    normalized_username=user.normalized_username
                ).count()
                > 0
            ):
                raise Exception(
                    "Normalized username {} (id {}) already exists. Can't continue.".format(
                        user.normalized_username, user.id
                    )
                )

            user.save()


def reverse_username_normalization(apps, schema_editor):
    User.objects.all().update(normalized_username="")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_add_normalized_username_field"),
    ]

    operations = [
        migrations.RunPython(
            update_normalized_username_field,
            reverse_code=reverse_username_normalization,
        )
    ]
