# Generated by Django 3.2.13 on 2022-06-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_calculate_normalized_usernames"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="normalized_username",
            field=models.CharField(blank=False, max_length=30, unique=True),
        ),
    ]
