# Generated by Django 3.2.15 on 2023-02-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_rename_profile_to_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("m", "Male"),
                    ("f", "Female"),
                    ("t", "Transgender"),
                    ("nb", "Non-binary/non-conforming"),
                    ("o", "Other/Prefer Not to Say"),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
