# Generated by Django 3.2.15 on 2023-02-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="addl_field_flag",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Flags if we've asked the user for additional information",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="company_size",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "----"),
                    (1, "Small/Start-up (1+ employees)"),
                    (9, "Small/Home office (1-9 employees)"),
                    (99, "Small (10-99 employees)"),
                    (999, "Small to medium-sized (100-999 employees)"),
                    (9999, "Medium-sized (1000-9999 employees)"),
                    (10000, "Large Enterprise (10,000+ employees)"),
                    (0, "Other (N/A or Don't know)"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="highest_education",
            field=models.CharField(
                blank=True,
                choices=[
                    (None, "----"),
                    ("Doctorate", "Doctorate"),
                    (
                        "Master's or professional degree",
                        "Master's or professional degree",
                    ),
                    ("Bachelor's degree", "Bachelor's degree"),
                    ("Associate degree", "Associate degree"),
                    ("Secondary/high school", "Secondary/high school"),
                    (
                        "Junior secondary/junior high/middle school",
                        "Junior secondary/junior high/middle school",
                    ),
                    ("Elementary/primary school", "Elementary/primary school"),
                    ("No formal education", "No formal education"),
                    ("Other education", "Other education"),
                ],
                default="",
                max_length=60,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_function",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="job_title",
            field=models.CharField(blank=True, default="", max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="leadership_level",
            field=models.CharField(blank=True, default="", max_length=60, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type_is_educator",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="The learner identifies as type Educator",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type_is_other",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="The learner identifies as type Other (not professional, student, or educator)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type_is_professional",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="The learner identifies as type Professional",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="type_is_student",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="The learner identifies as type Student",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="years_experience",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (None, "----"),
                    (2, "Less than 2 years"),
                    (5, "2-5 years"),
                    (10, "6 - 10 years"),
                    (15, "11 - 15 years"),
                    (20, "16 - 20 years"),
                    (21, "More than 20 years"),
                    (0, "Prefer not to say"),
                ],
                null=True,
            ),
        ),
    ]
