# Generated by Django 3.2.15 on 2023-02-21 15:51

from django.db import migrations, models


def add_birth_years(apps, schema_editor):
    """
    Adds a totally useless year of birth to existing records

    We want to have the birth year field populated but it needs to be obvious
    that the user hasn't supplied this and it needs to fail validation in the
    front end, so the year gets set to 3,000.
    """
    UserProfile = apps.get_model("users", "UserProfile")

    UserProfile.objects.filter(year_of_birth=None).update(year_of_birth=3000)


def remove_birth_years(apps, schema_editor):
    """Re-nulls the birth year on reversal"""
    UserProfile = apps.get_model("users", "UserProfile")

    UserProfile.objects.filter(year_of_birth=3000).update(year_of_birth=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_add_addl_profile_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="year_of_birth",
            field=models.IntegerField(),
        ),
        migrations.RunPython(
            add_birth_years,
            remove_birth_years,
        ),
    ]
