# Generated by Django 4.2.18 on 2025-03-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "users",
            "0024_rename_changeemailrequest_expires_on_confirmed_code_users_chang_expires_dbd4e5_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="global_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The SSO ID (usually a Keycloak UUID) for the user.",
                max_length=36,
            ),
        ),
    ]
