# Generated by Django 4.2.18 on 2025-02-19 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_changeemailrequest_expires_on_confirmed_code_users_chang_expires_dbd4e5_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_size',
            field=models.IntegerField(blank=True, choices=[('1', 'Small/Start-up (1+ employees)'), ('9', 'Small/Home office (1-9 employees)'), ('99', 'Small (10-99 employees)'), ('999', 'Small to medium-sized (100-999 employees)'), ('9999', 'Medium-sized (1000-9999 employees)'), ('10000', 'Large Enterprise (10,000+ employees)'), ('0', "Other (N/A or Don't know)")], null=True),
        ),
    ]
