# Generated by Django 4.2.18 on 2025-02-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_alter_userprofile_company_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="years_experience",
            field=models.IntegerField(
                blank=True,
                choices=[
                    ("2", "Less than 2 years"),
                    ("5", "2-5 years"),
                    ("10", "6 - 10 years"),
                    ("15", "11 - 15 years"),
                    ("20", "16 - 20 years"),
                    ("21", "More than 20 years"),
                    ("0", "Prefer not to say"),
                ],
                null=True,
            ),
        ),
    ]
