# Generated by Django 4.2.20 on 2025-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_set_username_to_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
