# Generated by Django 4.2.20 on 2025-05-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_add_orgs_and_contracts_models"),
        ("users", "0027_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="b2b_contracts",
            field=models.ManyToManyField(
                blank=True,
                help_text="The contracts the user is associated with.",
                related_name="users",
                to="b2b.contractpage",
            ),
        ),
    ]
