# Generated by Django 4.2.20 on 2025-04-26 01:15


from django.db import migrations


def set_completed_onboarding(apps, schema_editor):
    UserProfile = apps.get_model("users", "UserProfile")
    UserProfile.objects.all().update(completed_onboarding=True)


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_userprofile_completed_onboarding"),
    ]

    operations = [migrations.RunPython(set_completed_onboarding)]
