# Generated by Django 4.2.22 on 2025-07-23 21:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_populate_completed_onboarding"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"), name="user_email_unique"
            ),
        ),
    ]
