# Generated by Django 4.2.22 on 2025-07-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0032_add_case_insensitive_email_uniq"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
