# Generated by Django 4.2.22 on 2025-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_case_sensitive_email_uniq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='global_id',
            field=models.CharField(help_text='The SSO ID (usually a Keycloak UUID) for the user.', max_length=36, unique=True),
        ),
    ]
