# Generated by Django 4.2.24 on 2025-09-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_alter_user_global_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="global_id",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="The SSO ID (usually a Keycloak UUID) for the user.",
                max_length=36,
                null=True,
                unique=True,
            ),
        ),
    ]
