# Generated by Django 4.2.25 on 2025-10-08 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0009_contractpage_membership_type_and_more"),
        ("users", "0037_add_global_id_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="b2b_organizations",
            field=models.ManyToManyField(
                help_text="The organizations the user is associated with.",
                related_name="+",
                through="b2b.UserOrganization",
                to="b2b.organizationpage",
            ),
        ),
    ]
