# Generated by Django 4.2.25 on 2025-10-09 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0038_user_b2b_organizations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legaladdress",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="legaladdress",
            name="last_name",
        ),
    ]
