# Generated by Django 5.2.14 on 2026-06-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0039_remove_legaladdress_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_etl",
            field=models.BooleanField(
                default=False, help_text="The user is used by the Learn ETL process"
            ),
        ),
    ]
