# Generated by Django 5.2.15 on 2026-09-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0028_userb2bcontract"),
        ("users", "0043_legaladdress_first_name_last_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="b2b_contracts",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The contracts the user is associated with.",
                        related_name="users",
                        through="b2b.UserB2BContract",
                        to="b2b.contractpage",
                    ),
                ),
            ],
        )
    ]
