# Generated by Django 5.2.15 on 2026-09-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0029_userb2bcontract"),
        ("users", "0043_legaladdress_first_name_last_name"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="user",
                    name="b2b_contracts",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="The contracts the user is associated with.",
                        related_name="users",
                        through="b2b.UserB2BContract",
                        to="b2b.contractpage",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO b2b_userb2bcontract (user_id, contract_page_id)
                SELECT user_id, contractpage_id FROM users_user_b2b_contracts
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE users_user_b2b_contracts",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
