# Generated by Django 5.2.15 on 2026-07-28 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportComplianceLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("courseware_object_id", models.PositiveIntegerField()),
                ("decision", models.CharField(blank=True, default="", max_length=30)),
                (
                    "reason_code",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("encrypted_request", models.TextField()),
                ("encrypted_response", models.TextField()),
                (
                    "courseware_content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "courses"), ("model", "courserun")),
                            models.Q(("app_label", "courses"), ("model", "programrun")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_compliance_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
