# Generated by Django 4.2.20 on 2025-05-02 17:07

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="OrganizationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the organization", max_length=255
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Any useful extra information about the organization",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        help_text="The organization's logo. Will be displayed in the app in various places.",
                        upload_to="organization_logos",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContractPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the contract", max_length=255
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Any useful extra information about the contract",
                    ),
                ),
                (
                    "integration_type",
                    models.CharField(
                        choices=[("sso", "SSO"), ("non-sso", "Non-SSO")],
                        help_text="The type of integration for this contract",
                        max_length=255,
                    ),
                ),
                (
                    "contract_start",
                    models.DateField(
                        blank=True,
                        help_text="The start date of the contract.",
                        null=True,
                    ),
                ),
                (
                    "contract_end",
                    models.DateField(
                        blank=True, help_text="The end date of the contract.", null=True
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this contract is active or not. Date rules still apply.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        help_text="The organization this contract is with",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="b2b.organizationpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
