# Generated by Django 4.2.20 on 2025-04-24 20:33

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_add_base_organization_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Any useful extra information about the organization",
            ),
        ),
    ]
