# Generated by Django 4.2.21 on 2025-06-04 20:35

from django.db import migrations, models


def update_org_keys(apps, schema_editor):
    """
    Update the org keys.

    The next migration step adds a unique constraint, so generate these based
    on the first 3 of the org and the ID.
    """

    OrgPage = apps.get_model("b2b", "OrganizationPage")
    db = schema_editor.connection.alias

    for orgpage in OrgPage.objects.using(db).all():
        orgpage.org_key = f"{orgpage.name[0:3]}{orgpage.id}"
        orgpage.save()


def reverse_update_org_keys(apps, schema_editor):
    """No-op for reversal."""

    return


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0002_add_max_learners_price_fields_to_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationpage",
            name="org_key",
            field=models.CharField(
                default="bad",
                help_text="The short key used for the organization (for edX).",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(update_org_keys, reverse_update_org_keys),
        migrations.AlterField(
            model_name="organizationpage",
            name="org_key",
            field=models.CharField(
                help_text="The short key used for the organization (for edX).",
                max_length=10,
                unique=True,
            ),
        ),
    ]
