# Generated by Django 4.2.22 on 2025-07-31 19:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0003_add_org_key_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationpage",
            name="sso_organization_id",
            field=models.UUIDField(
                blank=True,
                help_text="The UUID for the organization in the SSO provider.",
                null=True,
            ),
        ),
    ]
