# Generated by Django 4.2.22 on 2025-08-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2b', '0004_add_sso_org_id_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpage',
            name='sso_alias',
            field=models.CharField(blank=True, default='', help_text="The organization's alias as set in the SSO provider.", max_length=255, verbose_name='Alias'),
        ),
    ]
