# Generated by Django 4.2.22 on 2025-08-06 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0036_alter_order_state"),
        ("b2b", "0004_add_sso_org_id_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscountContractAttachmentRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        help_text="The contract that the user was attached to.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="b2b.contractpage",
                    ),
                ),
                (
                    "discount",
                    models.ForeignKey(
                        help_text="The discount that was redemeed.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ecommerce.discount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user that redeemed the discount.",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
