# Generated by Django 4.2.22 on 2025-08-28 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0065_programcollection"),
        ("b2b", "0005_add_discount_attachment_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpage",
            name="programs",
            field=models.ManyToManyField(
                help_text="The programs associated with this contract.",
                related_name="contracts",
                to="courses.program",
            ),
        ),
    ]
