# Generated by Django 4.2.24 on 2025-09-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0006_add_contract_program_relationship"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contractpage",
            options={"verbose_name": "Contract", "verbose_name_plural": "Contracts"},
        ),
        migrations.AlterModelOptions(
            name="organizationpage",
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
            },
        ),
        migrations.AddConstraint(
            model_name="organizationpage",
            constraint=models.UniqueConstraint(
                fields=("sso_organization_id",), name="unique_sso_organization_id"
            ),
        ),
    ]
