# Generated by Django 4.2.24 on 2025-09-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0007_add_unique_constraint_fix_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationpage",
            name="org_key",
            field=models.CharField(
                help_text="The short key used for the organization (for edX).",
                max_length=30,
                unique=True,
            ),
        ),
    ]
