# Generated by Django 4.2.25 on 2025-10-08 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("b2b", "0008_increase_length_on_org_key_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpage",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("sso", "SSO"),
                    ("non-sso", "Non-SSO"),
                    ("managed", "Managed"),
                    ("code", "Enrollment Code"),
                    ("auto", "Auto Enrollment"),
                ],
                default="managed",
                help_text="The method to use to manage membership in the contract.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contractpage",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("sso", "SSO"),
                    ("non-sso", "Non-SSO"),
                    ("managed", "Managed"),
                    ("code", "Enrollment Code"),
                    ("auto", "Auto Enrollment"),
                ],
                help_text="The type of integration for this contract.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contractpage",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that owns this contract.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="b2b.organizationpage",
            ),
        ),
        migrations.CreateModel(
            name="UserOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keep_until_seen",
                    models.BooleanField(
                        default=False,
                        help_text="If True, the user will be kept in the organization until the organization is seen in their SSO data.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_users",
                        to="b2b.organizationpage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_organizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "organization")},
            },
        ),
    ]
