# Generated by Django 4.2.24 on 2025-09-24 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0008_increase_length_on_org_key_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contractpage",
            old_name="integration_type",
            new_name="membership_type",
        ),
        migrations.AlterField(
            model_name="contractpage",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("sso", "SSO"),
                    ("non-sso", "Non-SSO"),
                    ("managed", "Managed"),
                    ("code", "Enrollment Code"),
                    ("auto", "Auto Enrollment"),
                ],
                default="managed",
                help_text="The method to use to manage membership in the contract.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="contractpage",
            name="organization",
            field=models.ForeignKey(
                help_text="The organization that owns this contract.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contracts",
                to="b2b.organizationpage",
            ),
        ),
    ]
