# Generated by Django 4.2.25 on 2025-10-23 13:56

from django.core.cache import caches
from django.db import migrations
from django.db.models import F


def noop_reverse(apps, schema_editor):
    """No-op the reverse - we won't be able to figure out what orgs were there before."""

    return


def sync_contract_type_fields(apps, schema_editor):
    """
    Sync the contract type fields.

    We added a `membership_type` field alongside the `integration_type` field -
    the intent was that the `integration_type` field would go away in the near
    future. It still will, but until then, these need to be synced so that the
    user contract reconciliation stuff works properly. The model now enforces
    this; this fixes the old records and flushes the cached memberships from Redis
    so that it will do it again for everyone.
    """

    User = apps.get_model("users", "User")
    ContractPage = apps.get_model("b2b", "ContractPage")

    ContractPage.objects.update(membership_type=F("integration_type"))

    for user_id in User.objects.values_list("id", flat=True).all():
        caches["redis"].delete(f"org-membership-cache-{user_id}")


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0010_backfill_user_b2b_orgs"),
    ]

    operations = [
        migrations.RunPython(sync_contract_type_fields, noop_reverse),
    ]
