# Generated by Django 4.2.25 on 2025-10-31 19:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0011_sync_contract_type_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpage",
            name="welcome_message",
            field=models.CharField(
                blank=True, help_text="A welcome message for learners.", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="contractpage",
            name="welcome_message_extra",
            field=wagtail.fields.RichTextField(
                blank=True, help_text="Additional welcome message content for learners."
            ),
        ),
    ]
