# Generated by Django 4.2.25 on 2025-11-03 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0036_alter_order_state"),
        ("b2b", "0012_contractpage_welcome_message_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountcontractattachmentredemption",
            name="contract",
            field=models.ForeignKey(
                help_text="The contract that the user was attached to.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="code_redemptions",
                to="b2b.contractpage",
            ),
        ),
        migrations.AlterField(
            model_name="discountcontractattachmentredemption",
            name="discount",
            field=models.ForeignKey(
                help_text="The discount that was redemeed.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="contract_redemptions",
                to="ecommerce.discount",
            ),
        ),
        migrations.AlterField(
            model_name="discountcontractattachmentredemption",
            name="user",
            field=models.ForeignKey(
                help_text="The user that redeemed the discount.",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
