# Generated by Django 4.2.25 on 2025-11-07 18:37

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0074_populate_issue_date"),
        ("b2b", "0013_fix_contract_attachment_related_names"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractProgramItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "contract",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_programs",
                        to="b2b.contractpage",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_memberships",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contract Program Item",
                "verbose_name_plural": "Contract Program Items",
                "ordering": ["sort_order"],
                "unique_together": {("contract", "program")},
            },
        ),
    ]
