"""
Regenerate the contract page slugs. The model was changed to use the default
slug generation algorithm.
"""
# Generated by Django 5.1.15 on 2026-01-12 20:20

from django.db import migrations
from django.utils.text import slugify


def update_slugs(apps, schema_editor):
    """
    Re-run the slug generation for all pages - essentially, clear it and save.
    """

    ContractPage = apps.get_model("b2b", "ContractPage")

    for page in ContractPage.objects.all():
        page.slug = slugify(page.title)
        page.save()


def reverse_update_slugs(apps, schema_editor):
    """Use the old format if we need to reverse this."""

    ContractPage = apps.get_model("b2b", "ContractPage")

    for page in ContractPage.objects.prefetch_related("organization").all():
        page.slug = slugify(f"contract-{page.organization.id}-{page.title}")
        page.save()


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0016_remove_contractpage_programs"),
    ]

    operations = [
        migrations.RunPython(update_slugs, reverse_update_slugs),
    ]
