# Generated by Django 5.1.15 on 2026-02-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0017_regenerate_contract_page_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationpage",
            name="org_key_prefix",
            field=models.CharField(
                blank=True,
                default="course-v1:UAI_",
                help_text="The prefix to append to the org key (defaults to UAI_).",
                max_length=30,
            ),
        ),
    ]
