# Generated by Django 5.1.15 on 2026-02-11 14:10

from django.db import migrations

from courses.constants import UAI_COURSEWARE_ID_PREFIX


def backfill_org_key_prefixes(apps, schema_editor):
    """Fill existing org keys with the constant."""

    OrganizationPage = apps.get_model("b2b", "OrganizationPage")
    db_alias = schema_editor.connection.alias

    backfilled_orgs = OrganizationPage.objects.using(db_alias).all()
    for org in backfilled_orgs:
        org.org_key_prefix = UAI_COURSEWARE_ID_PREFIX

    OrganizationPage.objects.using(db_alias).bulk_update(
        backfilled_orgs, ["org_key_prefix"]
    )


def reverse_backfill(apps, schema_editor):
    """Reverse the backfill - clear the field."""

    OrganizationPage = apps.get_model("b2b", "OrganizationPage")
    db_alias = schema_editor.connection.alias

    backfilled_orgs = OrganizationPage.objects.using(db_alias).all()
    for org in backfilled_orgs:
        org.org_key_prefix = None

    OrganizationPage.objects.using(db_alias).bulk_update(
        backfilled_orgs, ["org_key_prefix"]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0018_add_org_key_to_organization"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill_org_key_prefixes, reverse_code=reverse_backfill
        )
    ]
