# Generated by Django 5.1.15 on 2026-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0019_backfill_org_key_prefixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractpage",
            name="google_sheet_target",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The URL for the Google Sheet to use to send codes and updates.",
            ),
        ),
        migrations.AddField(
            model_name="contractpage",
            name="google_sheet_target_tab",
            field=models.CharField(
                blank=True,
                default="Sheet1",
                help_text="The index or title of the worksheet in the Google Sheet to put the codes.",
            ),
        ),
    ]
