# Generated by Django 5.1.15 on 2026-03-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0019_backfill_org_key_prefixes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorganization",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="If True, the user is a manager of this organization and can access organization dashboard features.",
            ),
        ),
    ]
