# Generated by Django 5.2.14 on 2026-05-29 20:31

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0022_backfill_default_variants"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contractpage",
            managers=[
                ("active_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
