# Generated by Django 5.2.14 on 2026-06-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0022_backfill_default_variants"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to assign discount code to. This may correspond to a user which has not been created yet.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="last_reminder_sent_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the code last had a reminder email sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="redeemed_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the code was claimed. None indicates that it has been assigned, but not yet claimed.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discountcontractattachmentredemption",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that redeemed the discount.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
