# Generated by Django 5.2.14 on 2026-06-01 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_redemption_fields(apps, schema_editor):
    """
    Backfill assigned_email/assigned_name from the linked user record,
    and set redeemed_on to created_on for all existing redemption rows
    (pre-existing rows represent completed redemptions).
    """
    DiscountContractAttachmentRedemption = apps.get_model(
        "b2b", "DiscountContractAttachmentRedemption"
    )
    for redemption in DiscountContractAttachmentRedemption.objects.select_related(
        "user"
    ).all():
        redemption.assigned_email = redemption.user.email
        redemption.assigned_name = redemption.user.name
        redemption.redeemed_on = redemption.created_on
        redemption.save(
            update_fields=["assigned_email", "assigned_name", "redeemed_on"]
        )


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0023_add_active_objects_manager"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to assign discount code to. This may correspond to a user which has not been created yet.",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="assigned_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="last_reminder_sent_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the code last had a reminder email sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="redeemed_on",
            field=models.DateTimeField(
                blank=True,
                help_text="When the code was claimed. None indicates that it has been assigned, but not yet claimed.",
                null=True,
            ),
        ),
        migrations.RunPython(
            code=backfill_redemption_fields,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="discountcontractattachmentredemption",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user that redeemed the discount.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
