# Generated by Django 5.2.15 on 2026-06-30 14:52

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """If the model has an integration_type field, make it nullable; add it back otherwise."""


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0024_discountcontractattachmentredemption_assigned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractpage",
            name="integration_type",
            field=models.CharField(
                choices=[
                    ("sso", "SSO"),
                    ("non-sso", "Non-SSO"),
                    ("managed", "Managed"),
                    ("code", "Enrollment Code"),
                    ("auto", "Auto Enrollment"),
                ],
                help_text="The type of integration for this contract.",
                max_length=255,
                null=True,
                default="non-sso",
            ),
        ),
    ]
