# Generated by Django 5.2.15 on 2026-06-25 12:46

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """Swap sso/nonsso out for managed/code"""

    ContractPage = apps.get_model("b2b", "ContractPage")

    ContractPage.objects.filter(
        models.Q(integration_type="sso") | models.Q(membership_type="sso")
    ).update(membership_type="managed")
    ContractPage.objects.filter(
        models.Q(integration_type="non-sso") | models.Q(membership_type="non-sso")
    ).update(membership_type="code")


def reverse_func(apps, schema_editor):
    """Re-fill the integration_type field"""

    ContractPage = apps.get_model("b2b", "ContractPage")

    ContractPage.objects.update(integration_type=models.F("membership_type"))


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0024_discountcontractattachmentredemption_assigned_by_and_more"),
    ]

    operations = [
        migrations.RunPython(
            forwards_func,
            reverse_func,
        ),
        migrations.RemoveField(
            model_name="contractpage",
            name="integration_type",
        ),
        migrations.AlterField(
            model_name="contractpage",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("managed", "Managed"),
                    ("code", "Enrollment Code"),
                    ("auto", "Auto Enrollment"),
                ],
                default="managed",
                help_text="The method to use to manage membership in the contract.",
                max_length=255,
            ),
        ),
    ]
