# Generated by Django 5.2.15 on 2026-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0026_remove_sso_options_rename_existing"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="email_message_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mailgun message ID for the email sent to the user.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="email_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Mailgun status for the email sent to the user.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="discountcontractattachmentredemption",
            name="email_status_event_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
