# Generated by Django 5.2.15 on 2026-09-04 17:58

import django.db.models.deletion
from django.db import migrations, models

# Imported by name rather than as `mitol.common.utils.datetime.now_in_utc`,
# which is what makemigrations writes: mitol.common.utils re-exports the
# datetime *class*, so that dotted path resolves to it and the attribute
# lookup fails at import time.
from mitol.common.utils.datetime import now_in_utc

# Imported by name rather than as `mitol.common.utils.datetime.now_in_utc`,
# which is what makemigrations writes: mitol.common.utils re-exports the
# datetime *class*, so the dotted path resolves to that and the attribute
# lookup fails at import time.


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0027_discountcontractattachmentredemption_email_message_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationIdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "alias",
                    models.CharField(
                        help_text="The Keycloak IdP alias. Realm-wide, not per-organization.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[("saml", "SAML"), ("oidc", "OIDC")], max_length=8
                    ),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("testing", "Testing"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "internal_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Keycloak's internalId for the IdP instance.",
                        max_length=255,
                    ),
                ),
                (
                    "metadata_source",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The metadata URL, or the inline XML, the config was parsed from.",
                    ),
                ),
                (
                    "metadata_artifact",
                    models.JSONField(
                        blank=True,
                        help_text="The config map Keycloak parsed out of the metadata. Persisted so a partner's metadata endpoint going away can neither destroy config nor block a deploy.",
                        null=True,
                    ),
                ),
                ("metadata_fetched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_providers",
                        to="b2b.organizationpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrganizationOnboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("org_created", "Organization created"),
                            ("idp_configured", "Identity provider configured"),
                            ("idp_validated", "Identity provider validated"),
                            ("contract_ready", "Contract ready"),
                            ("live", "Live"),
                            ("blocked", "Blocked"),
                        ],
                        default="requested",
                        max_length=32,
                    ),
                ),
                (
                    "state_changed_at",
                    models.DateTimeField(default=now_in_utc),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Free-form operator notes; holds the reason when state is blocked.",
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="b2b.organizationpage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
