# Generated by Django 5.2.15 on 2026-09-11 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0027_discountcontractattachmentredemption_email_message_id_and_more"),
        # TODO: Need to see if this sort of dependency is allowed. Most of the time we rely on # noqa: FIX002, TD003, TD002
        # migrations.swappable_dependency(settings.AUTH_USER_MODEL) but I think that's just model existence
        ("users", "0029_add_b2b_contract_fk"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE users_user_b2b_contracts RENAME TO b2b_userb2bcontract",
                    reverse_sql="ALTER TABLE b2b_userb2bcontract RENAME TO users_user_b2b_contracts",
                ),
            ],
            state_operations=[
                migrations.CreateModel(
                    name="UserB2BContract",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "contract_page",
                            models.ForeignKey(
                                db_column="contractpage_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="b2b_contract_users",
                                to="b2b.contractpage",
                            ),
                        ),
                        (
                            "user",
                            models.ForeignKey(
                                db_column="user_id",
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="user_b2b_contracts",
                                to=settings.AUTH_USER_MODEL,
                            ),
                        ),
                    ],
                    options={
                        "unique_together": {("user", "contract_page")},
                    },
                ),
            ],
        ),
    ]
