# Generated by Django 5.2.17 on 2026-09-18 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0028_organizationidentityprovider_organizationonboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProvisioningAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "call_stack",
                    models.CharField(blank=True, default="", max_length=750, null=True),
                ),
                ("data_before", models.JSONField(blank=True, null=True)),
                ("data_after", models.JSONField(blank=True, null=True)),
                (
                    "identity_provider_alias",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("organization_created", "Organization created"),
                            ("organization_updated", "Organization updated"),
                            ("onboarding_changed", "Onboarding state changed"),
                            ("identity_provider_created", "Identity provider created"),
                            (
                                "identity_provider_transitioned",
                                "Identity provider state changed",
                            ),
                            (
                                "identity_provider_metadata_refreshed",
                                "Identity provider metadata refreshed",
                            ),
                            ("identity_provider_deleted", "Identity provider deleted"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "acting_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="provisioning_audits",
                        to="b2b.organizationpage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_on", "-id"],
            },
        ),
    ]
