# Generated by Django 5.2.15 on 2026-09-17 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0028_organizationidentityprovider_organizationonboarding"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserB2BContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="b2b_contract_users",
                        to="b2b.contractpage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_b2b_contracts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "contract_page")},
            },
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO b2b_userb2bcontract (user_id, contract_page_id)
                SELECT user_id, contractpage_id FROM users_user_b2b_contracts
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
