# Generated by Django 5.2.15 on 2026-09-15 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0029_userb2bcontract"),
    ]

    operations = [
        migrations.AddField(
            model_name="userb2bcontract",
            name="consent_modified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userb2bcontract",
            name="consented_to_data_sharing",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="userb2bcontract",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userb2bcontract",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
