# Generated by Django 5.2.17 on 2026-09-21 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0031_organizationprovisioningaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprovisioningaudit",
            name="action",
            field=models.CharField(
                choices=[
                    ("organization_created", "Organization created"),
                    ("organization_updated", "Organization updated"),
                    ("onboarding_changed", "Onboarding state changed"),
                    ("identity_provider_created", "Identity provider created"),
                    ("identity_provider_updated", "Identity provider updated"),
                    (
                        "identity_provider_transitioned",
                        "Identity provider state changed",
                    ),
                    (
                        "identity_provider_metadata_refreshed",
                        "Identity provider metadata refreshed",
                    ),
                    ("identity_provider_deleted", "Identity provider deleted"),
                ],
                max_length=64,
            ),
        ),
    ]
