# Generated by Django 5.2.17 on 2026-10-07 20:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0035_alter_organizationprovisioningaudit_action"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="contractpage",
            managers=[],
        ),
    ]
