USER_MSG_COOKIE_NAME = "user-message"
# Max age value = number of seconds
USER_MSG_COOKIE_MAX_AGE = 20
USER_MSG_TYPE_ENROLLED = "enrolled"
USER_MSG_TYPE_ENROLL_FAILED = "enroll-failed"
USER_MSG_TYPE_ENROLL_BLOCKED = "enroll-blocked"
USER_MSG_TYPE_ENROLL_DUPLICATED = "enroll-duplicated"
USER_MSG_TYPE_COMPLETED_AUTH = "completed-auth"
USER_MSG_TYPE_COURSE_NON_UPGRADABLE = "course-non-upgradable"
USER_MSG_TYPE_DISCOUNT_INVALID = "discount-invalid"

USER_MSG_TYPE_PAYMENT_DECLINED = "payment-declined"
USER_MSG_TYPE_PAYMENT_ERROR = "payment-error"
USER_MSG_TYPE_PAYMENT_CANCELLED = "payment-cancelled"
USER_MSG_TYPE_PAYMENT_REVIEW = "payment-review"
USER_MSG_TYPE_PAYMENT_ACCEPTED = "payment-accepted"
USER_MSG_TYPE_PAYMENT_ACCEPTED_NOVALUE = "payment-accepted-no-value"
USER_MSG_TYPE_PAYMENT_ERROR_UNKNOWN = "payment-error-unknown"

DISALLOWED_CURRENCY_CUBAN_PESO = "CUP"
DISALLOWED_CURRENCY_CUBAN_PESO_CONVERTED = "CUC"
DISALLOWED_CURRENCY_IRANIAN_RIAL = "IRR"
DISALLOWED_CURRENCY_SYRIAN_POUND = "SYP"
DISALLOWED_CURRENCY_NORTH_KOREAN_WON = "KPW"

DISALLOWED_CURRENCY_TYPES = [
    DISALLOWED_CURRENCY_CUBAN_PESO,
    DISALLOWED_CURRENCY_CUBAN_PESO_CONVERTED,
    DISALLOWED_CURRENCY_IRANIAN_RIAL,
    DISALLOWED_CURRENCY_SYRIAN_POUND,
    DISALLOWED_CURRENCY_NORTH_KOREAN_WON,
]

USER_REGISTRATION_FAILED_MSG = "Unable to register at this time, please try again later"
