# Generated by Django 3.1.12 on 2021-07-21 17:16

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        ("wagtailcore", "0062_comment_models_and_pagesubscription"),
        ("wagtailforms", "0004_add_verbose_name_plural"),
        ("wagtailredirects", "0006_redirect_increase_max_length"),
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoursePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    wagtail.core.fields.RichTextField(
                        blank=True,
                        help_text="The description shown on the product page",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page",
                        to="courses.course",
                    ),
                ),
                (
                    "feature_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be used where the course is featured or linked.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.DeleteModel(
            name="ProductPage",
        ),
    ]
