# Generated by Django 3.1.12 on 2021-08-16 09:26

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0008_move_pages_under_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="faculty_members",
            field=wagtail.core.fields.StreamField(
                [
                    (
                        "faculty_member",
                        wagtail.core.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.core.blocks.CharBlock(
                                        help_text="Name of the faculty member.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Profile image size must be at least 300x300 pixels."
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.core.blocks.RichTextBlock(
                                        help_text="A brief description about the faculty member."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="The faculty members to display on this page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="faculty_section_title",
            field=models.CharField(
                blank=True,
                default="Meet your instructors",
                help_text="The title text to display in the faculty cards section of the product page.",
                max_length=255,
                null=True,
            ),
        ),
    ]
