# Generated by Django 3.1.12 on 2021-08-24 08:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0010_coursepage_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="faculty_members",
            field=wagtail.fields.StreamField(
                [
                    (
                        "faculty_member",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "name",
                                    wagtail.blocks.CharBlock(
                                        help_text="Name of the faculty member.",
                                        max_length=100,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Profile image size must be at least 300x300 pixels."
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.RichTextBlock(
                                        help_text="A brief description about the faculty member."
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                help_text="The faculty members to display on this page",
                null=True,
            ),
        ),
    ]
