# Generated by Django 3.1.12 on 2021-09-17 12:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0011_product_faculty_members_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The description shown on the home page and product page.",
            ),
        ),
    ]
