# Generated by Django 3.2.5 on 2021-11-29 11:35

import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0023_add_choose_permissions"),
        ("cms", "0013_feature_img_aspect_ratio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="description",
            field=wagtail.fields.RichTextField(
                help_text="The description shown on the home page and product page. The recommended character limit is 1000 characters. Longer entries may not display nicely on the page."
            ),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="feature_image",
            field=models.ForeignKey(
                help_text="Image that will be used where the course is featured or linked. (The recommended dimensions for the image are 375x244)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="length",
            field=models.CharField(
                default="",
                help_text="A short description indicating how long it takes to complete (e.g. '4 weeks').",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="price",
            field=wagtail.fields.StreamField(
                [
                    (
                        "price_details",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        help="Displayed over the product detail page under the price tile.",
                                        max_length=150,
                                    ),
                                ),
                                (
                                    "link",
                                    wagtail.blocks.URLBlock(
                                        help="Specify the URL to redirect the user for the product's price details page.",
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                help_text="Specify the product price details.",
            ),
        ),
    ]
