# Generated by Django 3.2.10 on 2022-01-14 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0014_make_product_mandatory_fields_required"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeproductlink",
            options={},
        ),
        migrations.RemoveField(
            model_name="homeproductlink",
            name="sort_order",
        ),
    ]
