# Generated by Django 3.2.12 on 2022-05-06 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0015_remove_ordering_from_home_product_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="InnerResourcePage",
            fields=[
                (
                    "resourcepage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="cms.resourcepage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("cms.resourcepage",),
        ),
    ]
