# Generated by Django 3.2.14 on 2022-08-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0019_add_models_for_program_pages"),
        ("cms", "0019_remove_flexiblepricingrequestform_thank_you_text"),
    ]

    operations = []
