# Generated by Django 3.2.14 on 2022-08-04 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0013_backfill_paid_courserun"),
        ("cms", "0020_flexiblepricingrequestform_selected_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexiblepricingrequestform",
            name="selected_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="courses.program",
            ),
        ),
    ]
