# Generated by Django 3.2.14 on 2022-08-05 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0020_add_productpage_and_base_tables"),
        ("cms", "0021_flexiblepricingrequestform_selected_program"),
    ]

    operations = []
