# Generated by Django 3.2.15 on 2022-08-17 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0023_add_zero_discount_form_field"),
        (
            "cms",
            "0023_certificateindexpage_certificatepage_signatoryindexpage_signatorypage",
        ),
    ]

    operations = []
