# Generated by Django 3.2.15 on 2022-08-23 12:37

import logging

from django.db import migrations

log = logging.getLogger(__name__)


def fix_certificate_index_page(apps, schema_editor):
    """
    Get HomePage and Create or update Certificate Index Page. Fix slug name if already created
    """


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0025_modify_feature_image_blank"),
    ]

    operations = [
        migrations.RunPython(fix_certificate_index_page, migrations.RunPython.noop)
    ]
