# Generated by Django 3.2.18 on 2023-07-25 20:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0027_wagtail_v5_upgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructorIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="InstructorPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "instructor_name",
                    models.CharField(
                        default="",
                        help_text="The name of the instructor.",
                        max_length=255,
                    ),
                ),
                (
                    "instructor_title",
                    models.CharField(
                        blank=True,
                        help_text="The instructor's title (academic or otherwise).",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "instructor_bio_short",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="A short biography of the instructor. This will be shown in cards.",
                        null=True,
                    ),
                ),
                (
                    "instructor_bio_long",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="A longer biography of the instructor.",
                        null=True,
                    ),
                ),
                (
                    "feature_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Image that will be used where the instructor is featured or linked. (The recommended dimensions for the image are 375x244)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
