# Generated by Django 3.2.18 on 2023-08-10 14:50

from django.db import migrations


def move_short_to_longs(apps, schema_editor):
    InstructorPage = apps.get_model("cms", "InstructorPage")

    for page in InstructorPage.objects.all():
        page.instructor_bio_long = page.instructor_bio_short
        page.instructor_bio_short = ""
        page.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0029_add_linked_instructors_to_product_pages"),
    ]

    operations = [
        migrations.RunPython(move_short_to_longs, reverse_func),
    ]
