# Generated by Django 3.2.20 on 2023-08-17 15:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0030_add_faq_remove_faculty_reorder_things"),
        ("cms", "0030_move_instructor_short_bios_to_long"),
    ]

    operations = []
