# Generated by Django 3.2.23 on 2024-05-15 12:05
import csv

from django.db import migrations


def migrate_associate_existing_topics(apps, app_schema):
    """Pre-populate the existing course pages with the topics from their associated departments"""

    CoursesTopic = apps.get_model("courses", "CoursesTopic")

    with open('cms/data/CourseTopics.csv', 'r', newline='') as file:  # noqa: PTH123
        reader = csv.reader(file)
        parent_course_topics_row = next(reader, None)
        parent_topic_dict = {}
        for index, topic in enumerate(parent_course_topics_row):
            parent_topic, _ = CoursesTopic.objects.get_or_create(name=topic, parent=None)
            parent_topic_dict[index] = parent_topic.id
        for row in reader:
            for index, col in enumerate(row):
                if col:
                    CoursesTopic.objects.get_or_create(
                        parent_id=parent_topic_dict[index],
                        name=col
                    )


def delete_all_topics(apps, app_schema):
    CoursesTopic = apps.get_model("courses", "CoursesTopic")
    CoursesTopic.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_sitebanner'),
    ]

    operations = [
        migrations.RunPython(
            migrate_associate_existing_topics, delete_all_topics
        )
    ]
