# Generated by Django 3.2.23 on 2024-05-15 12:47

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0051_coursestopic'),
        ('cms', '0035_sitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The topics for this course page.', null=True, to='courses.CoursesTopic'),
        ),
    ]
