# Generated by Django 3.2.23 on 2024-05-15 12:05

from django.db import migrations


def migrate_associate_existing_topics(apps, app_schema):
    """Pre-populate the existing course pages with the topics from their associated departments"""

    CoursePage = apps.get_model("cms", "CoursePage")
    CoursesTopic = apps.get_model("courses", "CoursesTopic")
    Department = apps.get_model("courses", "Department")

    for course_page in CoursePage.objects.all():
        if course_page.course:
            topics = Department.objects.filter(course=course_page.course)
            for topic in topics:
                courses_topic = CoursesTopic.objects.create(name=topic.name)
                CoursePage.topics.through.objects.create(
                    coursepage_id=course_page.id, coursestopic_id=courses_topic.id
                )


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0036_coursepage_topics'),
    ]

    operations = [
        migrations.RunPython(
            migrate_associate_existing_topics, migrations.RunPython.noop
        )
    ]
