# Generated by Django 3.2.25 on 2024-05-22 13:08

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0051_coursestopic"),
        ("cms", "0036_populate_course_topics"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The topics for this course page.",
                null=True,
                to="courses.CoursesTopic",
            ),
        ),
    ]
