# Generated by Django 3.2.25 on 2024-08-27 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    This migration alters the linked_instructor_page field of the InstructorPageLink model to ensure that any
    linked instructor page is deleted when the InstructorPageLink is deleted from a ProductPage.
    """

    dependencies = [
        ("cms", "0037_coursepage_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorpagelink",
            name="linked_instructor_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="cms.instructorpage",
            ),
        ),
    ]
