# Generated by Django 4.2.16 on 2024-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0039_coursepage_max_weekly_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="max_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The maximum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="min_weeks",
            field=models.SmallIntegerField(
                blank=True,
                help_text="The minimum number of weeks required to complete the course/program.",
                null=True,
            ),
        ),
    ]
