# Generated by Django 4.2.16 on 2024-12-05 19:39
import re

from django.db import migrations


def populate_weekly_hours_fields(apps, schema_editor):
    CoursePage = apps.get_model("cms", "CoursePage")
    for page in CoursePage.objects.all():
        if page.effort:
            effort_str = page.effort.lower()
            effort_nums = re.findall(r"\d+", effort_str)
            if len(effort_nums) > 0:
                page.min_weekly_hours = effort_nums[0]
                page.max_weekly_hours = (
                    effort_nums[1] if len(effort_nums) > 1 else effort_nums[0]
                )
                page.save()

    ProgramPage = apps.get_model("cms", "ProgramPage")
    for page in ProgramPage.objects.all():
        if page.effort:
            effort_str = page.effort.lower()
            effort_nums = re.findall(r"\d+", effort_str)
            if len(effort_nums) > 0:
                page.min_weekly_hours = effort_nums[0]
                page.max_weekly_hours = (
                    effort_nums[1] if len(effort_nums) > 1 else effort_nums[0]
                )
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0041_populate_min_weeks'),
    ]

    operations = [
        migrations.RunPython(
            populate_weekly_hours_fields, reverse_code=migrations.RunPython.noop
        ),
    ]
