# Generated by Django 4.2.18 on 2025-03-11 19:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0060_alter_coursestopic_options'),
        ('cms', '0042_populate_weekly_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The topics for this course page.', limit_choices_to=models.Q(('parent', None), _negated=True), null=True, to='courses.coursestopic'),
        ),
        migrations.CreateModel(
            name='TopicsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_topics', to='courses.coursestopic')),
                ('parent_topic', models.ForeignKey(limit_choices_to={'parent': None}, on_delete=django.db.models.deletion.CASCADE, related_name='parent_topics', to='courses.coursestopic')),
            ],
        ),
        migrations.AddField(
            model_name='coursepage',
            name='topic_pairs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The topic pairs for this course page.', to='cms.topicspair'),
        ),
    ]
