# Generated by Django 4.2.18 on 2025-03-08 04:22

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_alter_coursestopic_parent_coursessubtopic'),
        ('cms', '0042_populate_weekly_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='sub_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The subtopics for this course page.', null=True, to='courses.coursessubtopic'),
        ),
    ]
