# Generated by Django 4.2.18 on 2025-03-12 14:21

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0059_alter_coursestopic_options_alter_coursestopic_parent"),
        ("cms", "0042_populate_weekly_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="The topics for this course page.",
                limit_choices_to=models.Q(("parent", None), _negated=True),
                null=True,
                to="courses.coursestopic",
            ),
        ),
    ]
