# Generated by Django 4.2.16 on 2024-12-11 16:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0042_populate_weekly_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="custom_tab",
            field=wagtail.fields.StreamField(
                [("custom_tab", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help": "Displayed as the tab name", "max_length": 50},
                    ),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("content", 1)]],
                        {},
                    ),
                },
                help_text="This is the custom tab for this course.",
            ),
        ),
    ]
