# Generated by Django 4.2.18 on 2025-03-11 02:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_alter_coursestopic_parent_coursessubtopic'),
        ('cms', '0043_coursepage_sub_topics'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicsPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_topic', to='courses.coursestopic')),
                ('parent_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_topic', to='courses.coursestopic')),
            ],
        ),
        migrations.AddField(
            model_name='coursepage',
            name='topic_pairs',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The parent and child topics for this course page.', null=True, to='cms.topicspair'),
        ),
    ]
