# Generated by Django 4.2.18 on 2025-03-12 15:49

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0060_alter_coursestopic_parent"),
        ("cms", "0043_alter_coursepage_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Select topic pairs (primary -> secondary) for this course page.",
                limit_choices_to=models.Q(("parent", None), _negated=True),
                null=True,
                to="courses.coursestopic",
            ),
        ),
    ]
