# Generated by Django 4.2.16 on 2024-12-12 19:43

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0043_coursepage_custom_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='custom_tab',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='custom_tabs',
            field=wagtail.fields.StreamField([('custom_tab', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help': 'Displayed as the tab name', 'max_length': 50}), 1: ('wagtail.blocks.CharBlock', (), {'help': 'id of this element for scrolling on the page. One word or more connected with a dash.'}), 2: ('wagtail.blocks.RichTextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('href_slug', 1), ('content', 2)]], {})}, help_text='This is the custom tab for this course.'),
        ),
    ]
