# Generated by Django 4.2.21 on 2025-06-23 18:47

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0062_update_courserun_name_unique"),
        ("cms", "0044_alter_coursepage_topics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="topics",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True,
                help_text="Select topic pairs (primary -> secondary) for this course page.",
                limit_choices_to=models.Q(("parent", None), _negated=True),
                to="courses.coursestopic",
            ),
        ),
    ]
