# Generated by Django 4.2.22 on 2025-07-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0048_alter_coursepage_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="include_in_learn_catalog",
            field=models.BooleanField(
                default=False,
                help_text="If true, Learn should include this in its catalog.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="ingest_content_files_for_ai",
            field=models.BooleanField(
                default=False,
                help_text="If true, allow the AI chatbots to ingest the course's content files.",
                null=True,
            ),
        ),
    ]
