# Generated by Django 4.2.24 on 2025-09-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0050_add_course_flag_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("singleline", "Single line text"),
                    ("multiline", "Multi-line text"),
                    ("email", "Email"),
                    ("number", "Number"),
                    ("url", "URL"),
                    ("checkbox", "Checkbox"),
                    ("checkboxes", "Checkboxes"),
                    ("dropdown", "Drop down"),
                    ("multiselect", "Multiple select"),
                    ("radio", "Radio buttons"),
                    ("date", "Date"),
                    ("datetime", "Date/time"),
                    ("hidden", "Hidden field"),
                    ("country", "Country Currency"),
                    ("iso_country", "Country Code"),
                ],
                max_length=20,
                verbose_name="Field Type",
            ),
        ),
    ]
