# Generated by Django 4.2.24 on 2025-09-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0051_alter_formfield_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='signatorypage',
            name='title_3',
            field=models.CharField(blank=True, help_text='Specify signatory thrid title in organization.', max_length=250, null=True),
        ),
    ]
