# Generated by Django 5.1.15 on 2025-12-22 21:19

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0052_signatorypage_title_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='what_you_learn',
            field=wagtail.fields.RichTextField(blank=True, help_text='*Required for Verifiable Credential generation. What you will learn from this course.', null=True),
        ),
        migrations.AlterField(
            model_name='programpage',
            name='what_you_learn',
            field=wagtail.fields.RichTextField(blank=True, help_text='*Required for Verifiable Credential generation. What you will learn from this course.', null=True),
        ),
    ]
