# Generated by Django 5.1.15 on 2026-01-08 08:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0053_alter_coursepage_what_you_learn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programpage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="The description shown on the home page and product page.",
                null=True,
            ),
        ),
    ]
