# Generated by Django 5.1.15 on 2026-02-03 16:52

import re
from django.db import migrations


def extract_numeric_prices(price_stream):
    """
    Extracts the first and second integer found in the text of the price StreamField block.
    Returns (min_price, max_price) as integers, or (None, None) if not found.
    """

    if not price_stream:
        return (None, None)
    for block in price_stream:
        text = block.value.get("text")
        if text:
            # Find all numbers in the string
            price_nums = re.findall(r"\d+", text)
            if price_nums:
                min_price = int(price_nums[0])
                max_price = int(price_nums[1]) if len(price_nums) > 1 else min_price
                return (min_price, max_price)
    return (None, None)


def populate_min_max_price(apps, schema_editor):
    CoursePage = apps.get_model("cms", "CoursePage")
    for course_page in CoursePage.objects.all():
        min_price, max_price = extract_numeric_prices(course_page.price)
        updated = False
        if course_page.min_price is None:
            course_page.min_price = min_price if min_price is not None else 0
            updated = True
        if course_page.max_price is None:
            course_page.max_price = max_price if max_price is not None else 0
            updated = True
        if updated:
            course_page.save(
                update_fields=[
                    f
                    for f in ["min_price", "max_price"]
                    if getattr(course_page, f) is not None
                ]
            )

    ProgramPage = apps.get_model("cms", "ProgramPage")
    for program in ProgramPage.objects.all():
        min_price, max_price = extract_numeric_prices(program.price)
        updated = False
        if program.min_price is None:
            program.min_price = min_price if min_price is not None else 0
            updated = True
        if program.max_price is None:
            program.max_price = max_price if max_price is not None else 0
            updated = True
        if updated:
            program.save(
                update_fields=[
                    f
                    for f in ["min_price", "max_price"]
                    if getattr(program, f) is not None
                ]
            )


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0054_alter_programpage_description"),
    ]

    operations = [
        migrations.RunPython(populate_min_max_price, migrations.RunPython.noop),
    ]
