# Generated by Django 5.1.15 on 2026-03-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0056_alter_coursepage_max_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="verifiable_credential_criteria",
            field=models.CharField(
                blank=True,
                help_text="For verifiable credentials issued for this certificate, this is the criteria narrative field. It should be something descriptive, like a list of completed courses, and may be plaintext or markdown",
                max_length=250,
                null=True,
            ),
        ),
    ]
