# Generated by Django 5.1.9 on 2026-03-20 00:00

from django.db import migrations, models


def set_include_in_learn_catalog_for_live_program_pages(apps, schema_editor):
    ProgramPage = apps.get_model("cms", "ProgramPage")
    ProgramPage.objects.filter(live=True).update(include_in_learn_catalog=True)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0057_certificatepage_should_provision_verifiable_credential_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="programpage",
            name="include_in_learn_catalog",
            field=models.BooleanField(
                default=False,
                help_text="If true, Learn should include this in its catalog.",
                null=True,
            ),
        ),
        migrations.RunPython(
            set_include_in_learn_catalog_for_live_program_pages,
            migrations.RunPython.noop,
        ),
    ]
