# Generated by Django 5.1.15 on 2026-04-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0058_programpage_include_in_learn_catalog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatepage",
            name="verifiable_credential_criteria",
            field=models.TextField(
                blank=True,
                help_text="For verifiable credentials issued for this certificate, this is the criteria narrative field. It should be something descriptive, like a list of completed courses, and may be plaintext or markdown. If it is not supplied, no verifiable credential will be provisioned for those certificates.",
                null=True,
            ),
        ),
    ]
