# Generated by Django 5.1.15 on 2026-04-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0059_alter_certificatepage_verifiable_credential_criteria"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_ai_enabled_support",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Get personalized help on assignments from AskTIM, powered by advanced AI.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_learn_by_doing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Practice core competencies through case studies, simulations, and hands-on tools.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_learn_from_others",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Connect with an international community of professionals working on real-world projects.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_learn_on_demand",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Access all course content online with complete flexibility to study at your own pace.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_realworld_learning",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Learn from faculty experts who emphasize practical application over theory.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hyl_choice_stackable_credentials",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Earn certificates at key milestones—module, course, and program—building a portfolio of expertise.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_ai_enabled_support",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Get personalized help on assignments from AskTIM, powered by advanced AI.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_learn_by_doing",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Practice core competencies through case studies, simulations, and hands-on tools.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_learn_from_others",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Connect with an international community of professionals working on real-world projects.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_learn_on_demand",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Access all course content online with complete flexibility to study at your own pace.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_realworld_learning",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Learn from faculty experts who emphasize practical application over theory.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hyl_choice_stackable_credentials",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Earn certificates at key milestones—module, course, and program—building a portfolio of expertise.",
                null=True,
            ),
        ),
    ]
