# Generated by Django 5.1.15 on 2026-05-07

from django.db import migrations, models


def get_program_product(program):
    """Return the active product for a program, or the first product if none are active."""
    products = list(program.products.all())
    if not products:
        return None

    return next((product for product in products if product.is_active), products[0])


def populate_program_list_price(apps, schema_editor):  # noqa: ARG001
    ProgramPage = apps.get_model("cms", "ProgramPage")

    for program_page in ProgramPage.objects.select_related("program").prefetch_related(
        "program__products"
    ):
        if program_page.list_price is not None:
            continue

        if program_page.program is None:
            continue

        product = get_program_product(program_page.program)
        if product is None:
            continue

        program_page.list_price = product.price
        program_page.save(update_fields=["list_price"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0060_add_hyl_choice_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="programpage",
            name="list_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specify the numeric list price for this program.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_program_list_price,
            migrations.RunPython.noop,
        ),
    ]

