# Generated by Django 5.1.15 on 2026-05-07
from collections import defaultdict

from django.db import migrations, models


def populate_program_list_price(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ProgramPage = apps.get_model("cms", "ProgramPage")
    Product = apps.get_model("ecommerce", "Product")

    program_pages = list(ProgramPage.objects.select_related("program"))
    program_ids = [program_page.program_id for program_page in program_pages]

    if not program_ids:
        return

    program_content_type = ContentType.objects.get(app_label="courses", model="program")
    products_by_program_id = defaultdict(list)
    for product in Product.objects.filter(
        content_type_id=program_content_type.id,
        object_id__in=program_ids,
    ).order_by("object_id", "id"):
        products_by_program_id[product.object_id].append(product)

    for program_page in program_pages:
        if program_page.list_price is not None:
            continue

        if program_page.program is None:
            continue

        products = products_by_program_id.get(program_page.program_id, [])
        product = next((product for product in products if product.is_active), None)
        if product is None and products:
            product = products[0]
        if product is None:
            continue

        program_page.list_price = product.price
        program_page.save(update_fields=["list_price"])


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0060_add_hyl_choice_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="programpage",
            name="list_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Specify the numeric list price for this program.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_program_list_price,
            migrations.RunPython.noop,
        ),
    ]
