# Generated by Django 5.1.15 on 2026-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0060_add_hyl_choice_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='listed_price',
            field=models.SmallIntegerField(default=0, help_text='Specify the product price. This is used by MIT Learn.'),
        ),
        migrations.AddField(
            model_name='programpage',
            name='listed_price',
            field=models.SmallIntegerField(default=0, help_text='Specify the product price. This is used by MIT Learn.'),
        ),
    ]
