# Generated by Django 5.1.15 on 2026-05-12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0061_programpage_list_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursepage",
            name="price",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="price",
        ),
    ]
