# Generated by Django 5.2.14 on 2026-05-14 12:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0061_programpage_list_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatepage",
            name="signatories",
            field=wagtail.fields.StreamField(
                [("signatory", 0)],
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["cms.SignatoryPage"], "required": True},
                    )
                },
                help_text="You can choose upto 7 signatories.",
            ),
        ),
    ]
