# Generated by Django 5.2.14 on 2026-06-01 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0062_alter_certificatepage_signatories'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DELETE FROM cms_signatorypage WHERE signature_image_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='signatorypage',
            name='signature_image',
            field=models.ForeignKey(blank=False, help_text='Signature image size must be at least 150x50 pixels.', null=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
