# Generated by Django 5.1.15 on 2026-06-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0062_alter_certificatepage_signatories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Specify the maximum product price. This is used by MIT Learn.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="coursepage",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Specify the minimum product price. This is used by MIT Learn.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="max_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Specify the maximum product price. This is used by MIT Learn.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Specify the minimum product price. This is used by MIT Learn.",
                max_digits=10,
            ),
        ),
    ]

