# Generated by Django 5.2.14 on 2026-06-01 14:09

import base64

from django.core.files.base import ContentFile
from django.db import migrations, models
from django.db.models import deletion


def backfill_missing_signatory_images(apps, _schema_editor):
    """Assign a fallback image to signatories with null signature_image."""

    SignatoryPage = apps.get_model("cms", "SignatoryPage")
    Image = apps.get_model("wagtailimages", "Image")

    missing_signatories = SignatoryPage.objects.filter(signature_image__isnull=True)
    if not missing_signatories.exists():
        return

    fallback_image = Image.objects.order_by("id").first()
    if fallback_image is None:
        # 1x1 transparent PNG used only if there are no existing images in the DB.
        png_bytes = base64.b64decode(
            "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO7Z8ioAAAAASUVORK5CYII="
        )
        fallback_image = Image(title="Missing signature placeholder")
        fallback_image.file.save(
            "missing-signature-placeholder.png",
            ContentFile(png_bytes),
            save=False,
        )
        fallback_image.save()

    missing_signatories.update(signature_image=fallback_image)


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0063_alter_coursepage_max_price_alter_coursepage_min_price_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill_missing_signatory_images,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="signatorypage",
            name="signature_image",
            field=models.ForeignKey(
                blank=False,
                help_text="Signature image size must be at least 150x50 pixels.",
                null=False,
                on_delete=deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
