# Generated by Django 5.2.15 on 2026-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0064_alter_signatorypage_signature_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificatepage",
            name="product_name",
            field=models.CharField(
                help_text="Specify the course/program name. Note: This is what will appear on the learner's certificate.",
                max_length=250,
                verbose_name="Certificate Title",
            ),
        ),
    ]
