# Generated by Django 5.2.15 on 2026-08-04 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0066_coursepage_show_stay_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursepage",
            name="price",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="price",
        ),
    ]
