# Generated by Django 5.2.15 on 2026-08-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0066_coursepage_show_stay_updated_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coursepage",
            name="show_stay_updated",
        ),
        migrations.RemoveField(
            model_name="programpage",
            name="show_stay_updated",
        ),
        migrations.AddField(
            model_name="coursepage",
            name="hubspot_form_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HubSpot form ID for this page's 'Stay Updated' sign-up form. Set to show the form on this page; leave blank to hide it.",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="programpage",
            name="hubspot_form_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HubSpot form ID for this page's 'Stay Updated' sign-up form. Set to show the form on this page; leave blank to hide it.",
                max_length=50,
            ),
        ),
    ]
