# Generated by Django 5.2.15 on 2026-09-15 11:32

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0067_remove_coursepage_show_stay_updated_and_more"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursepage",
            name="faq_url",
            field=models.URLField(
                blank=True,
                help_text="External link to a separate FAQ page (opens in a new tab on the legacy site). For on-page FAQs shown on MIT Learn, use the FAQs section below instead.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programpage",
            name="faq_url",
            field=models.URLField(
                blank=True,
                help_text="External link to a separate FAQ page (opens in a new tab on the legacy site). For on-page FAQs shown on MIT Learn, use the FAQs section below instead.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ProductPageFAQ",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "question",
                    models.TextField(help_text="The frequently asked question."),
                ),
                (
                    "answer",
                    wagtail.fields.RichTextField(
                        help_text="The answer. Supports links and basic formatting."
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faqs_list",
                        to="wagtailcore.page",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
