# Generated by Django 5.2.15 on 2026-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0069_add_product_page_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="verifiable_credential_description",
            field=models.TextField(
                blank=True,
                help_text="For verifiable credentials issued for this certificate, this is the description field. It is a template shared across every learner who earns this credential, so it should not include a specific learner's name. NOTE: this field is not yet wired into credential issuance (see mitodl/hq#13417).",
                null=True,
            ),
        ),
    ]
