# Generated by Django 5.2.15 on 2026-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0069_add_product_page_testimonial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificatepage",
            name="verifiable_credential_description",
            field=models.TextField(
                blank=True,
                help_text="1-2 sentences describing the course or program. This language serves as a template applied to the credential for every learner who completes the course and earns a certificate, so it should not include a specific learner's name.",
                null=True,
            ),
        ),
    ]
