# Generated by Django 5.2.17 on 2026-10-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0070_certificatepage_verifiable_credential_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursepage",
            name="show_course_outline",
            field=models.BooleanField(
                default=True,
                help_text="If true, Learn should show the course outline (modules) on the product page. Turn this off for courses whose module titles aren't written for a pre-purchase audience.",
            ),
        ),
    ]
