# Generated by Django 3.2.5 on 2021-12-07 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecommerce", "0002_product_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "courses"), ("model", "course_run")),
                    models.Q(("app_label", "courses"), ("model", "program_run")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
