# Generated by Django 3.2.12 on 2022-02-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0011_discount_discount_code"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="basketdiscount",
            constraint=models.UniqueConstraint(
                fields=("redeemed_by", "redeemed_basket"), name="unique_basket_discount"
            ),
        ),
    ]
