# Generated by Django 3.2.12 on 2022-03-02 20:36

import django.db.models.deletion
import django_fsm
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ecommerce", "0011_line_purchased_object"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclinedOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ecommerce.order",),
        ),
        migrations.CreateModel(
            name="ErroredOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ecommerce.order",),
        ),
        migrations.AlterField(
            model_name="basketdiscount",
            name="redeemed_basket",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="ecommerce.basket",
            ),
        ),
        migrations.AlterField(
            model_name="basketdiscount",
            name="redeemed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="basketdiscount",
            name="redeemed_discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="ecommerce.discount",
            ),
        ),
        migrations.AlterField(
            model_name="discountredemption",
            name="redeemed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discountredemption",
            name="redeemed_discount",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_redemptions",
                to="ecommerce.discount",
            ),
        ),
        migrations.AlterField(
            model_name="discountredemption",
            name="redeemed_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="discounts",
                to="ecommerce.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("declined", "Declined"),
                    ("errored", "Errored"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
