# Generated by Django 3.2.12 on 2022-03-04 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0012_basketdiscount_unique_basket_discount"),
        ("ecommerce", "0012_model_related_field_changes"),
    ]

    operations = []
