# Generated by Django 3.2.12 on 2022-03-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0013_merge_model_field_and_basketdiscount_changes"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.TextField(
                choices=[("payment", "payment"), ("refund", "refund")],
                default="payment",
                max_length=20,
            ),
        ),
    ]
