# Generated by Django 3.2.13 on 2022-07-07 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0015_add_review_status_to_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
