# Generated by Django 3.2.14 on 2022-07-15 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_update_discounts_add_flex_pricing_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="ecommerce.product",
            ),
        ),
    ]
