# Generated by Django 3.2.13 on 2022-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0016_update_discounts_add_flex_pricing_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="reason",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
