# Generated by Django 3.2.14 on 2022-07-28 22:41

from django.db import migrations

from ecommerce.db_utils import create_delete_rule, rollback_delete_rule


def product_protection_rules():
    """
    Helper function to create protection rules for product table,
    to prevent updates and deletes (but creates are still allowed)
    """
    table_name = "product"
    return [
        migrations.RunSQL(
            sql=create_delete_rule(table_name),
            reverse_sql=rollback_delete_rule(table_name),
        )
    ]


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0018_add_many_to_one_fk_discounts_to_products"),
    ]

    operations = [*product_protection_rules()]
