# Generated by Django 3.2.14 on 2022-08-02 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_db_protect_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('object_id', 'is_active')},
        ),
    ]
