# Generated by Django 3.2.14 on 2022-08-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0022_backfill_reference_number"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_object_id_validated",
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("object_id", "is_active", "content_type"),
                name="unique_purchasable_object",
            ),
        ),
    ]
