# Generated by Django 3.2.14 on 2022-08-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0023_alter_index_unique_object_id_validated"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="line",
            constraint=models.UniqueConstraint(
                fields=("order_id", "purchased_content_type", "purchased_object_id"),
                name="unique_order_purchased_object",
            ),
        ),
    ]
