# Generated by Django 3.2.14 on 2022-08-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0023_alter_index_unique_object_id_validated"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="activation_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, this discount code will not be redeemable before this date.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discount",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, this discount code will not be redeemable after this date.",
                null=True,
            ),
        ),
    ]
