# Generated by Django 3.2.15 on 2022-08-19 13:28
from django.db import migrations
from django.db.models.expressions import RawSQL


def backfill_transaction_id(apps, schema_editor):
    transaction = apps.get_model("ecommerce", "Transaction")

    transaction.objects.filter(transaction_type="payment").update(
        transaction_id=RawSQL("data->>'transaction_id'", ()),
    )
    transaction.objects.filter(transaction_type="refund").update(
        transaction_id=RawSQL("data->>'id'", ()),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0025_transaction_transaction_id"),
    ]

    operations = [
        migrations.RunPython(backfill_transaction_id, migrations.RunPython.noop),
    ]
