# Generated by Django 3.2.15 on 2022-08-19 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0026_backfill_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
