# Generated by Django 3.2.14 on 2022-08-17 14:25

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0028_alter_transaction_transaction_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartiallyRefundedOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("ecommerce.order",),
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=django_fsm.FSMField(
                choices=[
                    ("pending", "Pending"),
                    ("fulfilled", "Fulfilled"),
                    ("canceled", "Canceled"),
                    ("refunded", "Refunded"),
                    ("declined", "Declined"),
                    ("errored", "Errored"),
                    ("review", "Review"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
