# Generated by Django 3.2.15 on 2022-12-08 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0029_add_partially_refunded_state_to_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="for_flexible_pricing",
            field=models.BooleanField(default=False),
        ),
    ]
