# Generated by Django 3.2.15 on 2023-02-09 08:49

from django.db import migrations
from django.db.models import Q

from ecommerce.constants import (
    PAYMENT_TYPE_CUSTOMER_SUPPORT,
    PAYMENT_TYPE_FINANCIAL_ASSISTANCE,
    PAYMENT_TYPE_LEGACY,
    PAYMENT_TYPE_MARKETING,
    PAYMENT_TYPE_STAFF,
)


def backfill_payment_types(apps, schema_editor):
    discount = apps.get_model("ecommerce", "Discount")

    # financial-assistance have `for_flexible_pricing=True`
    discount.objects.filter(for_flexible_pricing=True).update(
        payment_type=PAYMENT_TYPE_FINANCIAL_ASSISTANCE
    )

    # customer-support discount codes start with `CS-`
    discount.objects.filter(discount_code__startswith="CS-").update(
        payment_type=PAYMENT_TYPE_CUSTOMER_SUPPORT
    )

    # staff discount codes start with `JPAL-`
    discount.objects.filter(discount_code__startswith="JPAL-").update(
        payment_type=PAYMENT_TYPE_STAFF
    )

    # legacy discounts start with `MM-prepaid-`
    discount.objects.filter(discount_code__startswith="MM-prepaid-").update(
        payment_type=PAYMENT_TYPE_LEGACY
    )

    # marketing discount codes have multiple start codes
    discount.objects.filter(
        Q(discount_code__startswith="MITALUM15-")
        | Q(discount_code__startswith="14750x-")
        | Q(discount_code__startswith="14740x-")
        | Q(discount_code__startswith="1473x-")
        | Q(discount_code__startswith="14310x-")
        | Q(discount_code__startswith="JPAL102x-")
        | Q(discount_code__startswith="CYB2022-")
        | Q(discount_code="CYBER2022")
    ).update(payment_type=PAYMENT_TYPE_MARKETING)


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0031_discount_payment_type"),
    ]

    operations = [
        migrations.RunPython(backfill_payment_types, migrations.RunPython.noop),
    ]
