# Generated by Django 3.2.15 on 2023-01-25 13:08

from django.db import migrations


def backfill_payment_type_for_financial_assistance(apps, schema_editor):
    Discount = apps.get_model("ecommerce", "Discount")
    Discount.objects.filter(for_flexible_pricing=True).update(payment_type="FA")


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0031_discount_payment_type"),
    ]

    operations = [
        migrations.RunPython(backfill_payment_type_for_financial_assistance, migrations.RunPython.noop),
    ]
