# Generated by Django 3.2.15 on 2023-02-09 08:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0032_backfill_payment_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discount",
            name="for_flexible_pricing",
        ),
    ]
