# Generated by Django 5.1.15 on 2026-01-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("ecommerce", "0036_alter_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="line",
            name="purchased_content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "courses"), ("model", "courserun")),
                    models.Q(("app_label", "courses"), ("model", "program")),
                    _connector="OR",
                ),
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    models.Q(("app_label", "courses"), ("model", "courserun")),
                    models.Q(("app_label", "courses"), ("model", "program")),
                    _connector="OR",
                ),
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
