# Generated by Django 5.1.15 on 2026-01-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0037_update_purchasble_object_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="is_program_discount",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Discount is only for creating verified course run enrollments for a program.",
                null=True,
            ),
        ),
    ]
