# Generated by Django 5.1.15 on 2026-03-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0038_add_program_discount_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="b2b_sheet_location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The location of this code in the B2B contract's code sheet.",
            ),
        ),
    ]
