# Generated by Django 5.2.15 on 2026-07-13 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0039_add_b2b_gsheet_index_to_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway_type",
            field=models.CharField(
                blank=True,
                default="CyberSource",
                help_text="The payment gateway used for this order. Must match one of the supported payment gateways in ol-django.",
                max_length=32,
            ),
        ),
    ]
