# Generated by Django 5.2.15 on 2026-07-30 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0039_add_b2b_gsheet_index_to_discount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="basket",
            name="anonymous_id",
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="basket",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basket",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="basket",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("anonymous_id__isnull", True), ("user__isnull", False)),
                    models.Q(("anonymous_id__isnull", False), ("user__isnull", True)),
                    _connector="OR",
                ),
                name="basket_user_xor_anonymous_id",
            ),
        ),
    ]
