# Generated by Django 5.2.15 on 2026-08-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_refund_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
