# Generated by Django 5.2.15 on 2026-07-16 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0040_add_payment_gateway_type_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=255)),
                ("event_data", models.JSONField()),
                (
                    "related_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ecommerce.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
