# Generated by Django 5.2.15 on 2026-08-05 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0040_basket_anonymous_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="gateway_type",
            field=models.CharField(
                blank=True,
                default="CyberSource",
                help_text="The payment gateway used for this order. Must match one of the supported payment gateways in ol-django.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="StripeEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("event_id", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(default="invalid.event", max_length=255),
                ),
                ("event_data", models.JSONField()),
                (
                    "related_order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="ecommerce.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
