# Generated by Django 5.2.15 on 2026-07-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0041_add_gateway_type_and_stripe_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "refund_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "enrolled_in_another_course",
                                "I enrolled in another course",
                            ),
                            ("course_not_as_expected", "Course is not what I expected"),
                            ("technical_difficulties", "Technical difficulties"),
                            ("financial_reasons", "Financial reasons"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("refund_reason_text", models.TextField(blank=True)),
                ("consent_given", models.BooleanField(default=False)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="ecommerce.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
