# Generated by Django 5.2.15 on 2026-08-20 20:49

from django.db import migrations


def deduplicate_products(apps, schema_editor):
    """
    Hard-delete duplicate products sharing the same (object_id, content_type).

    The previous constraint was partial (is_active=True only), so multiple
    inactive products may exist for the same purchasable object. The new
    constraint covers all rows, so duplicates must be removed first.

    Retention priority: active product first, then highest id (most recent).
    """
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            DELETE FROM ecommerce_product
            WHERE id NOT IN (
                SELECT DISTINCT ON (object_id, content_type_id) id
                FROM ecommerce_product
                ORDER BY object_id, content_type_id, is_active DESC, id DESC
            )
            """
        )


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0044_alter_product_unique_purchasable_object_pt1"),
    ]

    operations = [
        migrations.RunPython(
            deduplicate_products,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
