# Generated by Django 5.2.15 on 2026-08-20 22:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0045_refund_reason_text_max_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="refund_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("not_enough_time", "I do not have enough time"),
                    ("course_not_as_expected", "Course is not what I expected"),
                    ("technical_difficulties", "I had a technical issue"),
                    ("course_too_difficult", "Course is too difficult"),
                    ("purchased_by_mistake", "I purchased by mistake"),
                    ("prefer_not_to_say", "Prefer not to say"),
                    ("other", "Other"),
                    ("enrolled_in_another_course", "I enrolled in another course"),
                    ("financial_reasons", "Financial reasons"),
                ],
                max_length=100,
            ),
        ),
    ]
