# Generated by Django 5.2.15 on 2026-08-20 20:53

from django.db import migrations, models

from ecommerce.db_utils import create_delete_rule, rollback_delete_rule


class Migration(migrations.Migration):
    table_name = "product"

    dependencies = [
        ("ecommerce", "0045_alter_product_unique_purchasable_object_pt2"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("object_id", "content_type"),
                name="unique_purchasable_object",
            ),
        ),
        migrations.RunSQL(
            sql=create_delete_rule(table_name),
            reverse_sql=rollback_delete_rule(table_name),
        ),
    ]
