# Generated by Django 5.2.15 on 2026-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0046_alter_product_unique_purchasable_object_pt3"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="discounted_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=5,
                help_text="Post-discount price of one unit, recorded when the order was priced.",
                max_digits=20,
                null=True,
            ),
        ),
    ]
