# Generated by Django 5.2.15 on 2026-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0046_alter_product_unique_purchasable_object_pt3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refundrequest",
            name="refund_reason_text",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
