# Generated by Django 5.2.15 on 2026-08-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0048_backfill_line_discounted_unit_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
