# Generated by Django 5.2.15 on 2026-09-03 15:54

from django.db import migrations, models
from django.db.models import Count


def refuse_duplicate_links(apps, schema_editor):
    """
    Stop the migration while ecommerce_discountproduct holds duplicate
    (discount, product) pairs, which the constraint below cannot be added over.
    Nothing references a link row by id, so either copy of a pair can be
    deleted by hand before re-running.
    """
    DiscountProduct = apps.get_model("ecommerce", "DiscountProduct")
    duplicates = (
        DiscountProduct.objects.values("discount_id", "product_id")
        .annotate(copies=Count("id"))
        .filter(copies__gt=1)
        .order_by("discount_id", "product_id")
    )
    if duplicates.exists():
        pairs = ", ".join(
            f"(discount {dup['discount_id']}, product {dup['product_id']})"
            for dup in duplicates
        )
        msg = f"Remove the duplicate discount-product links first: {pairs}"
        raise RuntimeError(msg)


class Migration(migrations.Migration):
    dependencies = [
        ("ecommerce", "0054_paid_amount_off_discounts"),
    ]

    operations = [
        migrations.RunPython(refuse_duplicate_links, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="discountproduct",
            constraint=models.UniqueConstraint(
                fields=("discount", "product"), name="unique_discount_product"
            ),
        ),
    ]
