# Generated by Django 5.2.15 on 2026-09-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0028_organizationidentityprovider_organizationonboarding"),
        ("ecommerce", "0055_internal_redemption_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="basketitem",
            name="b2b_contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="b2b.contractpage",
            ),
        ),
        migrations.AddField(
            model_name="line",
            name="b2b_contract",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="b2b.contractpage",
            ),
        ),
    ]
