# Generated by Django 5.2.14 on 2026-05-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportedVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="ISO 639-1 language code for this run (e.g. 'en', 'zh', 'fr'). Leave blank for unspecified.",
                        max_length=8,
                    ),
                ),
                (
                    "variant_length",
                    models.CharField(
                        blank=True,
                        choices=[("", "Normal"), ("S", "Short"), ("L", "Long")],
                        db_index=True,
                        default="",
                        help_text="Variant: Describes the length of the run (short/long).",
                        max_length=1,
                    ),
                ),
                (
                    "variant_industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Original"),
                            ("E", "Energy"),
                            ("F", "Finance"),
                            ("HC", "Healthcare"),
                        ],
                        db_index=True,
                        default="",
                        help_text="Variant: Describes the industry the run is adapted for.",
                        max_length=3,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("active", models.BooleanField(blank=True, default=True)),
                (
                    "b2b_only",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Set if this variant only applies within a B2B context.",
                    ),
                ),
                (
                    "default_variant",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        verbose_name="Set if this set of options is the default.",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to=models.Q(
                            models.Q(("app_label", "courses"), ("model", "course")),
                            models.Q(("app_label", "b2b"), ("model", "contractpage")),
                            _connector="OR",
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="supportedvariant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("default_variant", True)),
                fields=("object_id", "content_type"),
                name="unique_default_primary_per_object",
                nulls_distinct=True,
            ),
        ),
    ]
