# Generated by Django 5.2.14 on 2026-05-29 20:33

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    """Change lengths from F to empty string before we drop that option"""

    SupportedVariant = apps.get_model("variants", "SupportedVariant")

    SupportedVariant.objects.filter(variant_length="F").update(variant_length="")


def backwards_func(apps, schema_editor):
    """No-op for reversal - won't know which ones were created by the migration."""


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0002_alter_supportedvariant_language_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
        migrations.AlterField(
            model_name="supportedvariant",
            name="variant_length",
            field=models.CharField(
                blank=True,
                choices=[("", "Full"), ("S", "Short")],
                db_index=True,
                default="",
                help_text="Variant: Describes the length of the run (short/long).",
                max_length=1,
            ),
        ),
    ]
