# Generated by Django 5.2.15 on 2026-06-16 14:26

from django.db import migrations, models


def add_code(apps, schema_editor):
    """Change refs to 'zh_CN' to 'zh_HANS', since that's what they're supposed to be."""

    model = apps.get_model("variants", "SupportedVariant")
    model.objects.filter(language="zh_CN").update(language="zh_HANS")


def del_code(apps, schema_editor):
    """Roll back 'zh_HANS' to 'zh_CN'."""

    model = apps.get_model("variants", "SupportedVariant")
    model.objects.filter(language="zh_HANS").update(language="zh_CN")


class Migration(migrations.Migration):
    dependencies = [
        ("variants", "0003_update_variant_length_enum"),
        ("courses", "0099_add_zh_hans_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportedvariant",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("af_ZA", "af_ZA"),
                    ("ar", "ar"),
                    ("az", "az"),
                    ("bo", "bo"),
                    ("da", "da"),
                    ("de", "de"),
                    ("de_DE", "de_DE"),
                    ("el", "el"),
                    ("es_419", "es_419"),
                    ("es_ES", "es_ES"),
                    ("en", "en"),
                    ("fa", "fa"),
                    ("fr", "fr"),
                    ("fr_CA", "fr_CA"),
                    ("he", "he"),
                    ("hi", "hi"),
                    ("hu", "hu"),
                    ("id", "id"),
                    ("it_IT", "it_IT"),
                    ("ja", "ja"),
                    ("ka", "ka"),
                    ("kk", "kk"),
                    ("ko", "ko"),
                    ("lv", "lv"),
                    ("nl", "nl"),
                    ("pl", "pl"),
                    ("pt_BR", "pt_BR"),
                    ("pt_PT", "pt_PT"),
                    ("ro", "ro"),
                    ("ru", "ru"),
                    ("sq", "sq"),
                    ("sv", "sv"),
                    ("sw", "sw"),
                    ("te", "te"),
                    ("th", "th"),
                    ("tr_TR", "tr_TR"),
                    ("uk", "uk"),
                    ("uz", "uz"),
                    ("vi", "vi"),
                    ("zh_CN", "zh_CN"),
                    ("zh_HANS", "zh_HANS"),
                    ("zh_HK", "zh_HK"),
                ],
                db_index=True,
                default="en",
                help_text="ISO 639-1 language code for this run (e.g. 'en', 'zh', 'fr'). Leave blank for unspecified.",
                max_length=8,
            ),
        ),
        migrations.RunPython(add_code, del_code),
    ]
