# Generated by Django 3.1.12 on 2021-08-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_allow_period_in_readable_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserunenrollment",
            name="change_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferred", "deferred"),
                    ("transferred", "transferred"),
                    ("refunded", "refunded"),
                    ("enrolled", "enrolled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="change_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("deferred", "deferred"),
                    ("transferred", "transferred"),
                    ("refunded", "refunded"),
                    ("enrolled", "enrolled"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
