# Generated by Django 3.1.12 on 2021-09-14 17:45

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_unenrolled_change_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCountry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocked_countries",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "blocked countries",
                "unique_together": {("course", "country")},
            },
        ),
    ]
