# Generated by Django 3.2 on 2021-09-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_unenrolled_change_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="It will be fetched from edX studio course details via sync course run data",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="enrollment_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="It will be fetched from edX studio course details via sync course run data",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="enrollment_start",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="It will be fetched from edX studio course details via sync course run data",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="It will be fetched from edX studio course details via sync course run data",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="title",
            field=models.CharField(
                help_text="It will be fetched from edX studio course details via sync course run data",
                max_length=255,
            ),
        ),
    ]
