# Generated by Django 3.2 on 2021-09-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_blockedcountry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="end_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The last day the course is active. This value is synced automatically with edX studio.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="enrollment_end",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The last day students can enroll. This value is synced automatically with edX studio.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="enrollment_start",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The first day students can enroll. This value is synced automatically with edX studio.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="start_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The day the course begins. This value is synced automatically with edX studio.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="title",
            field=models.CharField(
                help_text="The title of the course. This value is synced automatically with edX studio.",
                max_length=255,
            ),
        ),
    ]
