# Generated by Django 3.2.12 on 2022-03-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_courserunenrollment_emails_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="enrollment_mode",
            field=models.CharField(
                blank=True, default="verified", max_length=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="enrollment_mode",
            field=models.CharField(
                blank=True, default="verified", max_length=20, null=True
            ),
        ),
    ]
