# Generated by Django 3.2.12 on 2022-03-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0009_enrollment_add_mode_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserunenrollment",
            name="enrollment_mode",
            field=models.CharField(
                blank=True, default="audit", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="enrollment_mode",
            field=models.CharField(
                blank=True, default="audit", max_length=20, null=True
            ),
        ),
    ]
