# Generated by Django 3.2.12 on 2022-03-07 19:24

from django.db import migrations


def reset_enrollments(apps, schema_editor):
    CourseRunEnrollment = apps.get_model("courses", "CourseRunEnrollment")
    ProgramEnrollment = apps.get_model("courses", "ProgramEnrollment")

    CourseRunEnrollment.objects.filter(enrollment_mode="verified").update(
        enrollment_mode="audit"
    )
    ProgramEnrollment.objects.filter(enrollment_mode="verified").update(
        enrollment_mode="audit"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0010_enrollment_update_default_mode"),
    ]

    operations = [
        migrations.RunPython(reset_enrollments),
    ]
