# Generated by Django 3.2.14 on 2022-07-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0011_fix_default_enrollment_mode_for_existing_enrollments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programenrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.program",
            ),
        ),
    ]
