# Generated by Django 3.2.14 on 2022-07-28 20:52

from django.db import migrations


def backfill_paidcourserun(apps, schema_editor):
    """Backfill PaidCourseRun for existing orders"""
    PaidCourseRun = apps.get_model("courses", "PaidCourseRun")
    CourseRun = apps.get_model("courses", "CourseRun")
    Order = apps.get_model("ecommerce", "Order")
    ContentType = apps.get_model("contenttypes", "ContentType")

    for order in Order.objects.filter(state__in=["fulfilled", "review"]):
        # couldn't use order.purchased_runs here from app defined model
        content_type = ContentType.objects.get_for_model(CourseRun)
        run_objects = order.lines.filter(purchased_content_type=content_type)
        course_run_ids = [run_obj.purchased_object_id for run_obj in run_objects]
        course_runs_by_id = CourseRun.objects.in_bulk(course_run_ids)
        
        for run_obj in run_objects:
            course_run = course_runs_by_id.get(run_obj.purchased_object_id)
            if course_run:
                PaidCourseRun.objects.get_or_create(
                    order=order, course_run=course_run, user=order.purchaser
                )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0012_paidcourserun"),
    ]

    operations = [
        migrations.RunPython(backfill_paidcourserun, migrations.RunPython.noop),
    ]
