# Generated by Django 3.2.14 on 2022-08-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0013_backfill_paid_courserun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="run_tag",
            field=models.TextField(
                help_text="A string that identifies the set of runs that this run belongs to (example: 'R2')",
                max_length=100,
            ),
        ),
    ]
