# Generated by Django 3.2.14 on 2022-08-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_courserun_run_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="upgrade_deadline",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The date beyond which the learner can not enroll in paid course mode.",
                null=True,
            ),
        ),
    ]
