# Generated by Django 3.2.14 on 2022-08-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0012_add_models_for_program_pages"),
        ("courses", "0014_alter_courserun_run_tag"),
    ]

    operations = []
