# Generated by Django 3.2.14 on 2022-08-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0014_alter_courserun_run_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programenrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.program",
            ),
        ),
    ]
