# Generated by Django 3.2.14 on 2022-08-05 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0015_update_related_name_for_program_enrollments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programenrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.program"
            ),
        ),
    ]
