# Generated by Django 3.2.15 on 2022-08-29 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("courses", "0018_courseruncertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseruncertificate",
            name="certificate_page_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.pagerevision",
            ),
        ),
    ]
