# Generated by Django 3.2.15 on 2022-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0018_courseruncertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="self_paced_certificates",
            field=models.BooleanField(default=False),
        ),
    ]
