# Generated by Django 3.2.15 on 2022-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_courseruncertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="is_self_paced",
            field=models.BooleanField(default=False),
        ),
    ]
