# Generated by Django 3.2.15 on 2022-08-29 08:44

from django.db import migrations, models
import django.db.models.deletion


def set_current_certificate_revision(apps, schema_editor):
    """
    Fetch all CourseRunCertificates and update certificate_page_revision to latest revision
    """
    from cms.models import CertificatePage
    from courses.models import CourseRunCertificate

    course_run_certificates = CourseRunCertificate.objects.all()
    for cert in course_run_certificates:
        certificate_page = (
            cert.course_run.course.page.get_children()
            .type(CertificatePage)
            .live()
            .first()
            if cert.course_run.course.page
            else None
        )
        if certificate_page:
            cert.certificate_page_revision = (
                certificate_page.specific.get_latest_revision()
            )
    CourseRunCertificate.objects.bulk_update(
        course_run_certificates, ["certificate_page_revision"]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        ("courses", "0019_add_is_self_paced_course_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseruncertificate",
            name="certificate_page_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.pagerevision",
            ),
        ),
        migrations.RunPython(
            set_current_certificate_revision, migrations.RunPython.noop
        ),
    ]
