# Generated by Django 3.2.15 on 2022-09-29 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailcore", "0066_collection_management_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0020_courseruncertificate_certificate_page_revision"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCertificate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_revoked",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates whether or not the certificate is revoked",
                        verbose_name="revoked",
                    ),
                ),
                (
                    "certificate_page_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.pagerevision",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "program")},
            },
        ),
    ]
