# Generated by Django 3.2.15 on 2022-10-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0021_programcertificate"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramRequirement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=255, unique=True)),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("program_root", "Program Root"),
                            ("operator", "Operator"),
                            ("course", "Course"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("all_of", "All of"),
                            ("min_number_of", "Minimum # of"),
                        ],
                        max_length=13,
                        null=True,
                    ),
                ),
                ("operator_value", models.CharField(max_length=100, null=True)),
                ("title", models.TextField(null=True, blank=True, default="")),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_programs",
                        to="courses.course",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_requirements",
                        to="courses.program",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="programrequirement",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("course__isnull", True),
                        ("depth", 1),
                        ("node_type", "program_root"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("depth__gt", 1),
                        ("node_type", "operator"),
                        ("operator__isnull", False),
                    ),
                    models.Q(
                        ("course__isnull", False),
                        ("depth__gt", 1),
                        ("node_type", "course"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="courses_programrequirement_node_check",
            ),
        ),
        migrations.AddConstraint(
            model_name="programrequirement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("depth", 1)),
                fields=("program", "depth"),
                name="courses_programrequirement_root_uniq",
            ),
        ),
        migrations.AlterIndexTogether(
            name="programrequirement",
            index_together={("program", "course"), ("course", "program")},
        ),
    ]
