# Generated by Django 3.2.15 on 2022-11-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0022_programrequirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartnerSchool",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
