# Generated by Django 3.2.15 on 2022-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0028_alter_certificate_models_make_page_revision_blankable"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="certificate_available_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The day certificates should be available to users. This value is synced automatically with edX studio.",
                null=True,
            ),
        ),
    ]
