# Generated by Django 3.2.18 on 2023-06-23 13:12

from django.db import migrations
from courses.models import CourseRunEnrollment, CourseRunCertificate
from openedx.constants import EDX_ENROLLMENT_VERIFIED_MODE


def backfill_enrollments_from_certificates(apps, schema_editor):

    certificates = CourseRunCertificate.objects.all()
    for certificate in certificates:
        CourseRunEnrollment.all_objects.get_or_create(
            user=certificate.user,
            run=certificate.course_run,
            defaults=dict(
                change_status=None,
                edx_enrolled=True,
                edx_emails_subscription=False,
                enrollment_mode=EDX_ENROLLMENT_VERIFIED_MODE,
            ),
        )


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_remove_course_position_in_program"),
    ]

    operations = [
        migrations.RunPython(
            backfill_enrollments_from_certificates, migrations.RunPython.noop
        ),
    ]
