# Generated by Django 3.2.18 on 2023-06-26 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0032_add_related_programs_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programenrollment",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="courses.program",
            ),
        ),
    ]
