# Generated by Django 3.2.18 on 2023-06-23 13:12

from django.db import migrations

from openedx.constants import EDX_ENROLLMENT_VERIFIED_MODE


def backfill_enrollments_from_certificates(apps, schema_editor):
    CourseRunEnrollment = apps.get_model("courses", "CourseRunEnrollment")
    CourseRunCertificate = apps.get_model("courses", "CourseRunCertificate")

    certificates = CourseRunCertificate.objects.all()
    for certificate in certificates:
        CourseRunEnrollment.objects.get_or_create(
            user=certificate.user,
            run=certificate.course_run,
            defaults=dict(  # noqa: C408
                change_status=None,
                edx_enrolled=True,
                edx_emails_subscription=False,
                enrollment_mode=EDX_ENROLLMENT_VERIFIED_MODE,
            ),
        )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0033_populate_letter_grades"),
    ]

    operations = [
        migrations.RunPython(
            backfill_enrollments_from_certificates, migrations.RunPython.noop
        ),
    ]
