# Generated by Django 3.2.18 on 2023-06-28 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0033_add_related_name_to_program_enrollments"),
        ("courses", "0034_backfill_enrollments_from_certificates"),
    ]

    operations = []
