# Generated by Django 3.2.18 on 2023-07-10 15:41

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    ProgramRequirement = apps.get_model("courses", "ProgramRequirement")
    db_alias = schema_editor.connection.alias
    update_reqs = (
        ProgramRequirement.objects.using(db_alias)
        .filter(depth=2, title="Elective Courses")
        .all()
    )

    for requirement in update_reqs:
        requirement.elective_flag = True

    ProgramRequirement.objects.using(db_alias).bulk_update(
        update_reqs, ["elective_flag"]
    )


def reverse_func(apps, schema_editor):
    # just here to make this reversible - the field goes away on down so nothing to do here
    return


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0036_update_letter_grades_for_dedp"),
    ]

    operations = [
        migrations.AddField(
            model_name="programrequirement",
            name="elective_flag",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.RunPython(
            forwards_func,
            reverse_func,
        ),
    ]
