# Generated by Django 3.2.18 on 2023-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0038_populate_letter_grades_3T2022"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="type_label",
            field=models.CharField(
                blank=True,
                default="Series",
                help_text="Type/group the program belongs to (i.e. MicroMasters™, Series, etc.)",
                max_length=255,
            ),
        ),
    ]
