# Generated by Django 3.2.18 on 2023-08-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    """Renames CourseTopic ot Department and adds it as a field to the Program model."""

    dependencies = [
        ("courses", "0039_program_program_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseTopic",
            new_name="Department",
        ),
        migrations.RemoveField(
            model_name="course",
            name="topics",
        ),
        migrations.AddField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(blank=True, to="courses.Department"),
        ),
        migrations.AddField(
            model_name="program",
            name="departments",
            field=models.ManyToManyField(blank=True, to="courses.Department"),
        ),
    ]
