# Generated by Django 3.2.18 on 2023-08-02 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0039_program_program_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseTopic',
            new_name='CourseDepartment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topics',
        ),
        migrations.AddField(
            model_name='course',
            name='departments',
            field=models.ManyToManyField(blank=True, to='courses.CourseDepartment'),
        ),
    ]
