# Generated by Django 3.2.18 on 2023-08-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0040_populate_none_letter_grades_for_DEDP"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CourseTopic",
            new_name="Department",
        ),
        migrations.RemoveField(
            model_name="course",
            name="topics",
        ),
        migrations.AddField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(blank=True, to="courses.Department"),
        ),
        migrations.AddField(
            model_name="program",
            name="departments",
            field=models.ManyToManyField(blank=True, to="courses.Department"),
        ),
    ]
