# Generated by Django 3.2.20 on 2023-08-22 15:30

from django.db import migrations


class Migration(migrations.Migration):
    """Adds ordering to the Course and Program model in order to support pagination."""

    dependencies = [
        ("courses", "0041_rename_topics_add_to_programs"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="program",
            options={"ordering": ["id"]},
        ),
    ]
