# Generated by Django 3.2.20 on 2023-09-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0042_add_ordering_to_course_and_program"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="live",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="program",
            name="live",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
