# Generated by Django 3.2.20 on 2023-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0043_alter_course_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='live',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
