# Generated by Django 3.2.23 on 2024-02-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0044_alter_courserun_live"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserunenrollmentaudit",
            name="modified_by",
            field=models.CharField(blank=True, default="", max_length=750, null=True),
        ),
        migrations.AddField(
            model_name="courserungradeaudit",
            name="modified_by",
            field=models.CharField(blank=True, default="", max_length=750, null=True),
        ),
        migrations.AddField(
            model_name="programenrollmentaudit",
            name="modified_by",
            field=models.CharField(blank=True, default="", max_length=750, null=True),
        ),
    ]
