# Generated by Django 3.2.23 on 2024-03-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0046_audit_rename_call_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(to="courses.Department"),
        ),
        migrations.AlterField(
            model_name="program",
            name="departments",
            field=models.ManyToManyField(to="courses.Department"),
        ),
    ]
