# Generated by Django 3.2.23 on 2024-03-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0048_populate_department_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="department",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
