# Generated by Django 3.2.23 on 2024-03-27 15:35

from django.db import migrations
from django.utils.text import slugify


def generate_slug(apps, schema):
    Department = apps.get_model("courses", "Department")
    for department in Department.objects.all():
        department.slug = slugify(department.name)
        department.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0048_add_department_slug"),
    ]

    operations = [
        migrations.RunPython(generate_slug, reverse_code=migrations.RunPython.noop),
    ]
