# Generated by Django 3.2.25 on 2024-08-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0053_reactivate_wrong_program_enrollments"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="availability",
            field=models.CharField(
                choices=[("anytime", "anytime"), ("dated", "dated")],
                default="anytime",
                max_length=255,
            ),
        ),
    ]
