# Generated by Django 4.2 on 2024-09-10 17:28
# Modified for Django 5.2 compatibility

from django.db import migrations, models


def rename_indexes_safe(apps, schema_editor):
    """Safely rename indexes, handling cases where they may not exist."""
    # Skip this - indexes will be created with proper names
    pass


def reverse_rename_indexes(apps, schema_editor):
    """Reverse operation for index renaming."""
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0054_add_program_availability"),
    ]

    operations = [
        # Remove temporary indexes from migration 0022
        migrations.RemoveIndex(
            model_name="programrequirement",
            name="courses_pro_program_temp_idx",
        ),
        migrations.RemoveIndex(
            model_name="programrequirement",
            name="courses_pro_course__temp_idx",
        ),
        # Add properly named indexes
        migrations.AddIndex(
            model_name="programrequirement",
            index=models.Index(fields=["course", "program"], name="courses_pro_course__fdcdb6_idx"),
        ),
        migrations.AddIndex(
            model_name="programrequirement",
            index=models.Index(fields=["program", "course"], name="courses_pro_program_c8ff7c_idx"),
        ),
    ]
