# Generated by Django 4.2 on 2024-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0055_rename_programrequirement_program_course_courses_pro_program_c8ff7c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="availability",
            field=models.CharField(
                choices=[("dated", "dated"), ("anytime", "anytime")],
                default="anytime",
                max_length=255,
            ),
        ),
    ]
