# Generated by Django 4.2.15 on 2024-09-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0056_program_end_date_program_enrollment_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="end_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="program",
            name="start_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
