# Generated by Django 4.2.18 on 2025-02-06 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0057_alter_program_end_date_alter_program_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["readable_id"]},
        ),
    ]
