# Generated by Django 4.2.18 on 2025-03-11 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0058_alter_course_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestopic',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.coursestopic'),
        ),
    ]
