# Generated by Django 4.2.18 on 2025-03-12 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0058_alter_course_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coursestopic",
            options={"ordering": ["parent__name", "name"]},
        ),
        migrations.AlterField(
            model_name="coursestopic",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="courses.coursestopic",
            ),
        ),
    ]
