# Generated by Django 4.2.18 on 2025-03-11 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0059_alter_coursestopic_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursestopic',
            options={'ordering': ['parent']},
        ),
    ]
