# Generated by Django 4.2.20 on 2025-05-02 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_add_orgs_and_contracts_models"),
        ("courses", "0060_alter_coursestopic_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="b2b_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_runs",
                to="b2b.contractpage",
            ),
        ),
    ]
