# Generated by Django 4.2.21 on 2025-06-04 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0061_add_b2b_contract_link_to_courseruns"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courserun",
            unique_together={("course", "courseware_id", "run_tag")},
        ),
    ]
