# Generated by Django 4.2.22 on 2025-07-02 18:33
# Modified for Django 5.2 compatibility

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0063_add_program_requirement_support"),
    ]

    operations = [
        # Remove the old index_together setting
        migrations.AlterIndexTogether(
            name="programrequirement",
            index_together=set(),
        ),
        # Add named indexes explicitly
        migrations.AddIndex(
            model_name="programrequirement",
            index=models.Index(fields=["program", "required_program"], name="courses_pro_program_18e9ef_idx"),
        ),
        migrations.AddIndex(
            model_name="programrequirement",
            index=models.Index(fields=["required_program", "program"], name="courses_pro_require_99b956_idx"),
        ),
    ]
