# Generated by Django 4.2.22 on 2025-07-21 12:30

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('courses', '0064_rename_programrequirement_program_required_program_courses_pro_program_18e9ef_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCollection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Description of the program collection')),
                ('programs', models.ManyToManyField(blank=True, help_text='Programs included in this collection', to='courses.program')),
            ],
            options={
                'verbose_name': 'Program Collection',
                'verbose_name_plural': 'Program Collections',
            },
            bases=('wagtailcore.page',),
        ),
    ]
