# Generated by Django 4.2.22 on 2025-07-15 17:43

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0064_rename_programrequirement_program_required_program_courses_pro_program_18e9ef_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the program collection", max_length=255
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="Description of the program collection"
                    ),
                ),
                (
                    "programs",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Programs included in this collection",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Collection",
                "verbose_name_plural": "Program Collections",
                "ordering": ["title"],
            },
        ),
    ]
