# Generated by Django 4.2.22 on 2025-08-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0065_programcollection"),
    ]

    operations = [
        migrations.AddField(
            model_name="program",
            name="b2b_only",
            field=models.BooleanField(
                default=False, help_text="Indicates if the program is B2B only"
            ),
        ),
    ]
