# Generated by Django 4.2.22 on 2025-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "courses",
            "0064_rename_programrequirement_program_required_program_courses_pro_program_18e9ef_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="include_in_learn_catalog",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, Learn should include this in its catalog.",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="ingest_content_files_for_ai",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="If true, allow the AI chatbots to ingest the course's content files.",
            ),
        ),
    ]
