# Generated by Django 4.2.25 on 2025-10-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0067_program_courses_pro_live_e5a870_idx_and_more'),
    ]

    operations = [
        # First create the new model
        migrations.CreateModel(
            name='ProgramCollectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of this program within the collection (lower numbers appear first)')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='courses.programcollection')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='courses.program')),
            ],
            options={
                'verbose_name': 'Program Collection Item',
                'verbose_name_plural': 'Program Collection Items',
                'ordering': ['order'],
                'unique_together': {('collection', 'program')},
            },
        ),
        # Copy data from the old relationship to the new one (using correct table name)
        migrations.RunSQL(
            "INSERT INTO courses_programcollectionitem (collection_id, program_id, \"order\") "
            "SELECT collection_id, program_id, 0 FROM courses_programcollectionprogram",
            reverse_sql="DELETE FROM courses_programcollectionitem"
        ),
        # Manually drop the old table 
        migrations.RunSQL(
            "DROP TABLE courses_programcollectionprogram CASCADE",
            reverse_sql="CREATE TABLE courses_programcollectionprogram (id serial PRIMARY KEY, collection_id integer, program_id integer)"
        ),
        # Remove the field from the model state without trying to drop any database tables
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='programcollection',
                    name='programs',
                ),
            ],
            database_operations=[
                # No database operations needed since we already dropped the table manually
            ],
        ),
    ]