# Generated by Django 4.2.25 on 2025-10-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0067_program_courses_pro_live_e5a870_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="departments",
            field=models.ManyToManyField(
                related_name="courses", to="courses.department"
            ),
        ),
        migrations.AlterField(
            model_name="program",
            name="departments",
            field=models.ManyToManyField(
                related_name="programs", to="courses.department"
            ),
        ),
    ]
