# Generated by Django 4.2.25 on 2025-10-09 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0067_program_courses_pro_live_e5a870_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCollectionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_items",
                        to="courses.programcollection",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_memberships",
                        to="courses.program",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Collection Item",
                "verbose_name_plural": "Program Collection Items",
                "ordering": ["sort_order"],
                "unique_together": {("collection", "program")},
            },
        ),
        migrations.RunSQL(
            "INSERT INTO courses_programcollectionitem (collection_id, program_id, sort_order) "
            "SELECT programcollection_id, program_id, "
            "ROW_NUMBER() OVER (PARTITION BY programcollection_id ORDER BY p.title) - 1 as sort_order "
            "FROM courses_programcollection_programs pcp "
            "JOIN courses_program p ON pcp.program_id = p.id",
            reverse_sql="DELETE FROM courses_programcollectionitem",
        ),
        migrations.RunSQL(
            "DROP TABLE courses_programcollection_programs CASCADE",
            reverse_sql="CREATE TABLE courses_programcollection_programs (id serial PRIMARY KEY, programcollection_id integer, program_id integer)",
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="programcollection",
                    name="programs",
                ),
            ],
            database_operations=[
            ],
        ),
    ]
