# Generated by Django 4.2.25 on 2025-10-14 15:40

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0068_department_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="is_source_run",
            field=models.BooleanField(
                default=False,
                help_text='Designate this run as a "source" run for contract re-runs of the course.',
            ),
        ),
        migrations.AlterModelOptions(
            name="programcollectionitem",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Program Collection Item",
                "verbose_name_plural": "Program Collection Items",
            },
        ),
        migrations.AlterField(
            model_name="programcollectionitem",
            name="collection",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="courses.programcollection",
            ),
        ),
    ]
