# Generated by Django 4.2.25 on 2025-10-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0068_department_related_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="is_source_run",
            field=models.BooleanField(
                default=False,
                help_text='Designate this run as a "source" run for contract re-runs of the course.',
            ),
        ),
    ]
