# Generated by Django 4.2.25 on 2025-10-09 19:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


def copy_order_to_sort_order(apps, schema_editor):
    """Copy data from order field to sort_order field and set alphabetical ordering"""
    ProgramCollectionItem = apps.get_model('courses', 'ProgramCollectionItem')
    ProgramCollection = apps.get_model('courses', 'ProgramCollection')

    # For each collection, get its items and order them alphabetically by program title
    for collection in ProgramCollection.objects.all():
        # Get all items for this collection and order by program title
        items = list(ProgramCollectionItem.objects.filter(collection=collection).select_related('program'))

        # Sort items alphabetically by program title
        items.sort(key=lambda item: item.program.title.lower())

        # Update sort_order with alphabetical ordering
        for index, item in enumerate(items):
            item.sort_order = index
            item.save(update_fields=['sort_order'])


def reverse_copy_order_to_sort_order(apps, schema_editor):
    """Copy data from sort_order field back to order field"""
    ProgramCollectionItem = apps.get_model('courses', 'ProgramCollectionItem')
    for item in ProgramCollectionItem.objects.all():
        item.order = item.sort_order
        item.save(update_fields=['order'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0068_add_program_collection_ordering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programcollectionitem',
            options={'ordering': ['sort_order'], 'verbose_name': 'Program Collection Item', 'verbose_name_plural': 'Program Collection Items'},
        ),
        migrations.AddField(
            model_name='programcollectionitem',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(
            copy_order_to_sort_order,
            reverse_copy_order_to_sort_order,
        ),
        migrations.RemoveField(
            model_name='programcollectionitem',
            name='order',
        ),
        migrations.AlterField(
            model_name='programcollectionitem',
            name='collection',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='courses.programcollection'),
        ),
    ]
