# Generated by Django 4.2.25 on 2025-10-09 19:35

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0070_add_program_collection_ordering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="programcollectionitem",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Program Collection Item",
                "verbose_name_plural": "Program Collection Items",
            },
        ),
        migrations.AlterField(
            model_name="programcollectionitem",
            name="collection",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="courses.programcollection",
            ),
        ),
    ]
