# Generated by Django 4.2.25 on 2025-10-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0071_update_program_collection_for_wagtail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programcollectionitem",
            name="sort_order",
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
