# Generated by Django 4.2.25 on 2025-10-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0072_alter_programcollectionitem_sort_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseruncertificate",
            name="issue_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="programcertificate",
            name="issue_date",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
