# Generated by Django 4.2.25 on 2025-10-21 14:59

from django.db import migrations


def populate_issue_date(apps, schema):
    CourseRunCertificate = apps.get_model("courses", "CourseRunCertificate")
    for certificate in CourseRunCertificate.objects.all():
        if certificate.issue_date is None:
            certificate.issue_date = certificate.created_on
            certificate.save(update_fields=["issue_date"])

    ProgramCertificate = apps.get_model("courses", "ProgramCertificate")
    for certificate in ProgramCertificate.objects.all():
        if certificate.issue_date is None:
            certificate.issue_date = certificate.created_on
            certificate.save(update_fields=["issue_date"])


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0073_courseruncertificate_issue_date_and_more"),
    ]

    operations = [
        migrations.RunPython(
            populate_issue_date, reverse_code=migrations.RunPython.noop
        ),
    ]
