# Generated by Django 4.2.25 on 2025-11-24 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0074_populate_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserungrade",
            name="grade",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(2.0),
                ]
            ),
        ),
    ]
