# Generated by Django 5.1.15 on 2025-12-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0075_update_course_run_grade_allow_extra_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseruncertificate',
            name='verifiable_credential',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programcertificate',
            name='verifiable_credential',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
