# Generated by Django 5.1.15 on 2025-12-16 16:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0075_update_course_run_grade_allow_extra_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiableCredential",
            fields=[
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "credential_data",
                    models.JSONField(
                        help_text="JSON data representing the verifiable credential"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="courseruncertificate",
            name="verifiable_credential",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.verifiablecredential",
            ),
        ),
        migrations.AddField(
            model_name="programcertificate",
            name="verifiable_credential",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.verifiablecredential",
            ),
        ),
    ]
