# Generated by Django 5.1.15 on 2026-02-05 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0079_remove_courserun_courseware_url_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserungrade",
            name="course_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="courses.courserun",
            ),
        ),
    ]
