# Generated by Django 5.1.15 on 2026-02-10 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0080_set_grade_run_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserungrade",
            name="letter_grade",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
