# Generated by Django 5.1.15 on 2026-02-13 14:37

from django.db import migrations


def populate_issue_date(apps, schema):
    CourseRunCertificate = apps.get_model("courses", "CourseRunCertificate")
    for certificate in CourseRunCertificate.objects.all():
        if certificate.issue_date is None:
            certificate.issue_date = certificate.created_on
            certificate.save(update_fields=["issue_date"])

    ProgramCertificate = apps.get_model("courses", "ProgramCertificate")
    for certificate in ProgramCertificate.objects.all():
        if certificate.issue_date is None:
            certificate.issue_date = certificate.created_on
            certificate.save(update_fields=["issue_date"])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0080_set_grade_run_related_name'),
    ]

    operations = [
        migrations.RunPython(
            populate_issue_date, reverse_code=migrations.RunPython.noop
        ),
    ]
