# Generated by Django 5.1.15 on 2026-02-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0080_set_grade_run_related_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programrequirement",
            name="path",
            field=models.CharField(db_collation="C", max_length=255, unique=True),
        ),
    ]
