# Generated by Django 5.1.15 on 2026-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0081_alter_courserungrade_letter_grade'),
        ('courses', '0081_set_program_requirement_path_collation'),
    ]

    operations = [
    ]
