# Generated by Django 5.1.15 on 2026-02-13 14:37

from django.db import migrations, models


def populate_issue_date(apps, schema):
    CourseRunCertificate = apps.get_model("courses", "CourseRunCertificate")
    CourseRunCertificate.objects.filter(issue_date__isnull=True).update(
        issue_date=models.F("created_on")
    )

    ProgramCertificate = apps.get_model("courses", "ProgramCertificate")
    ProgramCertificate.objects.filter(issue_date__isnull=True).update(
        issue_date=models.F("created_on")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0082_merge_0081"),
    ]

    operations = [
        migrations.RunPython(
            populate_issue_date, reverse_code=migrations.RunPython.noop
        ),
    ]
