# Generated by Django 5.1.15 on 2026-02-20 21:51

from django.contrib.contenttypes.models import ContentType
from django.db import migrations

from openedx.constants import EDX_ENROLLMENT_AUDIT_MODE, EDX_ENROLLMENT_VERIFIED_MODE


def generate_modes_for_coursewares(apps, schema_editor):
    """
    Generate default enrollment modes and attach them to course runs and programs.

    By default, we have "audit" and "verified" modes, and everything has an audit
    mode. Things with products should also have verified modes.
    """

    EnrollmentMode = apps.get_model("courses", "EnrollmentMode")
    CourseRun = apps.get_model("courses", "CourseRun")
    Program = apps.get_model("courses", "Program")
    Product = apps.get_model("ecommerce", "Product")

    course_run_contenttype = ContentType.objects.get_for_model(CourseRun)
    program_contenttype = ContentType.objects.get_for_model(Program)

    audit_mode = EnrollmentMode.objects.create(
        mode_slug=EDX_ENROLLMENT_AUDIT_MODE,
        mode_display_name=EDX_ENROLLMENT_AUDIT_MODE,
        requires_payment=False,
    )
    verified_mode = EnrollmentMode.objects.create(
        mode_slug=EDX_ENROLLMENT_VERIFIED_MODE,
        mode_display_name=EDX_ENROLLMENT_VERIFIED_MODE,
        requires_payment=True,
    )

    for run in CourseRun.objects.all():
        run.enrollment_modes.add(audit_mode)
        if Product.objects.filter(
            object_id=run.id, content_type_id=course_run_contenttype.id
        ).exists():
            run.enrollment_modes.add(verified_mode)

        run.save()

    for run in Program.objects.all():
        run.enrollment_modes.add(audit_mode)
        if Product.objects.filter(
            object_id=run.id, content_type_id=program_contenttype.id
        ).exists():
            run.enrollment_modes.add(verified_mode)

        run.save()


def remove_modes(apps, schema_editor):
    """Remove all the modes."""

    EnrollmentMode = apps.get_model("courses", "EnrollmentMode")

    EnrollmentMode.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0083_add_enrollment_modes"),
    ]

    operations = [
        migrations.RunPython(generate_modes_for_coursewares, remove_modes),
    ]
