# Generated by Django 5.1.15 on 2026-02-13 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0083_certificate_issue_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseruncertificate",
            name="issue_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="programcertificate",
            name="issue_date",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
