# Generated by Django 5.1.15 on 2026-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0084_certificate_issue_date_set_deafault"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentMode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_slug",
                    models.CharField(
                        blank=True, default="audit", max_length=255, unique=True
                    ),
                ),
                (
                    "mode_display_name",
                    models.CharField(blank=True, default="audit", max_length=255),
                ),
                ("requires_payment", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AddField(
            model_name="courserun",
            name="enrollment_modes",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="courses.enrollmentmode"
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="enrollment_modes",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="courses.enrollmentmode"
            ),
        ),
    ]
