# Generated by Django 5.1.15 on 2026-03-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0089_alter_course_departments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="program",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="programs", to="courses.department"
            ),
        ),
    ]
