# Generated by Django 5.1.15 on 2026-04-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0090_alter_program_departments"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerschool",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
