# Generated by Django 5.1.15 on 2026-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0091_add_soft_delete_to_partner_schools"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserunenrollment",
            name="enrollment_mode",
            field=models.CharField(default="audit", max_length=20),
        ),
        migrations.AlterField(
            model_name="programenrollment",
            name="enrollment_mode",
            field=models.CharField(default="audit", max_length=20),
        ),
    ]
