# Generated by Django 5.1.15 on 2026-04-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0021_userorganization_is_manager"),
        ("courses", "0092_enrollment_mode_non_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="is_primary_language",
            field=models.BooleanField(
                default=False,
                help_text="Designates this run as the primary-language version for its run-tag group. The primary run is used as the canonical run when grouping language variants. If no run in a group is marked primary, the oldest run by creation date is treated as primary.",
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="language",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="ISO 639-1 language code for this run (e.g. 'en', 'zh', 'fr'). Leave blank for unspecified.",
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("b2b_contract__isnull", True), ("language__isnull", False)
                ),
                fields=("course", "courseware_id", "run_tag", "language"),
                name="unique_courserun_course_runtag_language",
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("b2b_contract__isnull", True),
                    ("is_primary_language", True),
                    ("language__isnull", False),
                ),
                fields=("course", "run_tag", "is_primary_language"),
                name="unique_courserun_course_runtag_language_primary",
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("b2b_contract__isnull", False), ("language__isnull", False)
                ),
                fields=(
                    "course",
                    "courseware_id",
                    "run_tag",
                    "language",
                    "b2b_contract",
                ),
                name="unique_courserun_course_runtag_language_b2b",
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("b2b_contract__isnull", False),
                    ("is_primary_language", True),
                    ("language__isnull", False),
                ),
                fields=("course", "run_tag", "is_primary_language", "b2b_contract"),
                name="unique_courserun_course_runtag_language_primary_b2b",
            ),
        ),
    ]
