# Generated by Django 5.1.15 on 2026-04-30 23:38

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0021_userorganization_is_manager"),
        ("courses", "0093_add_language_fields_to_courserun"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="courserun",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_courserun_course_runtag_language",
        ),
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_courserun_course_coursewareid_runtag_language",
        ),
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_courserun_course_runtag_language_primary",
        ),
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_courserun_course_runtag_language_b2b",
        ),
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_courserun_course_runtag_language_primary_b2b",
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary_language", True)),
                fields=("course", "run_tag", "is_source_run", "b2b_contract"),
                name="unique_primary_language_per_group",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("language", ""), _negated=True),
                fields=(
                    "course",
                    "run_tag",
                    "language",
                    "is_source_run",
                    "b2b_contract",
                ),
                name="unique_language_per_group",
                nulls_distinct=False,
            ),
        ),
    ]
