# Generated by Django 5.2.14 on 2026-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0021_userorganization_is_manager"),
        ("courses", "0094_update_courserun_language_constraints"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="courserun",
            name="unique_language_per_group",
        ),
        migrations.AddField(
            model_name="courserun",
            name="variant_industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Original"),
                    ("E", "Energy"),
                    ("F", "Finance"),
                    ("HC", "Healthcare"),
                ],
                db_index=True,
                default="",
                help_text="Variant: Describes the industry the run is adapted for.",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="variant_length",
            field=models.CharField(
                blank=True,
                choices=[("", "Normal"), ("S", "Short"), ("L", "Long")],
                db_index=True,
                default="",
                help_text="Variant: Describes the length of the run (short/long).",
                max_length=1,
            ),
        ),
        migrations.AddConstraint(
            model_name="courserun",
            constraint=models.UniqueConstraint(
                condition=models.Q(("language", ""), _negated=True),
                fields=(
                    "course",
                    "run_tag",
                    "language",
                    "is_source_run",
                    "b2b_contract",
                    "variant_length",
                    "variant_industry",
                ),
                name="unique_language_per_group",
                nulls_distinct=False,
            ),
        ),
    ]
