# Generated by Django 5.2.14 on 2026-05-22 17:05

from django.db import migrations


def forwards_func(apps, schema_editor):
    """Set the default language to `en`, add sane default variant sets."""

    Course = apps.get_model("courses", "Course")
    SupportedVariant = apps.get_model("variants", "SupportedVariant")
    ContentType = apps.get_model("contenttypes", "ContentType")

    course_content_type = ContentType.objects.get_for_model(Course)
    course_sv_ids = SupportedVariant.objects.filter(
        content_type=course_content_type, default_variant=True
    ).values_list("object_id", flat=True)

    default_sv_options = {
        "active": True,
        "b2b_only": False,
        "default_variant": True,
        "language": "en",
        "variant_length": "",
        "variant_industry": "",
    }

    for course in Course.objects.exclude(pk__in=course_sv_ids).all():
        SupportedVariant.objects.create(
            content_type=course_content_type, object_id=course.id, **default_sv_options
        )


def backwards_func(apps, schema_editor):
    """No-op for reversal - won't know which ones were created by the migration."""


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0095_add_courserun_course_variant_options"),
        ("variants", "0001_add_supported_variant_model"),
    ]

    operations = [migrations.RunPython(forwards_func, backwards_func)]
