# Generated by Django 5.2.14 on 2026-05-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0096_add_variant_defaults"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("af_ZA", "af_ZA"),
                    ("ar", "ar"),
                    ("az", "az"),
                    ("bo", "bo"),
                    ("da", "da"),
                    ("de", "de"),
                    ("de_DE", "de_DE"),
                    ("el", "el"),
                    ("es_419", "es_419"),
                    ("es_ES", "es_ES"),
                    ("en", "en"),
                    ("fa", "fa"),
                    ("fr", "fr"),
                    ("fr_CA", "fr_CA"),
                    ("he", "he"),
                    ("hi", "hi"),
                    ("hu", "hu"),
                    ("id", "id"),
                    ("it_IT", "it_IT"),
                    ("ja", "ja"),
                    ("ka", "ka"),
                    ("kk", "kk"),
                    ("ko", "ko"),
                    ("lv", "lv"),
                    ("nl", "nl"),
                    ("pl", "pl"),
                    ("pt_BR", "pt_BR"),
                    ("pt_PT", "pt_PT"),
                    ("ro", "ro"),
                    ("ru", "ru"),
                    ("sq", "sq"),
                    ("sv", "sv"),
                    ("sw", "sw"),
                    ("te", "te"),
                    ("th", "th"),
                    ("tr_TR", "tr_TR"),
                    ("uk", "uk"),
                    ("uz", "uz"),
                    ("vi", "vi"),
                    ("zh_CN", "zh_CN"),
                    ("zh_HK", "zh_HK"),
                ],
                db_index=True,
                default="en",
                help_text="ISO 639-1 language code for this run (e.g. 'en', 'zh', 'fr'). Leave blank for unspecified.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="variant_length",
            field=models.CharField(
                blank=True,
                choices=[("", "Normal"), ("S", "Short"), ("F", "Full")],
                db_index=True,
                default="",
                help_text="Variant: Describes the length of the run (short/long).",
                max_length=1,
            ),
        ),
    ]
