# Generated by Django 5.2.15 on 2026-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0099_add_zh_hans_language_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="edx_enrollment_retry_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="How many times retry_failed_edx_enrollments has attempted to enroll this record via the edX API. Once this reaches OPENEDX_ENROLLMENT_REPAIR_MAX_RETRIES the enrollment is no longer retried automatically.",
            ),
        ),
    ]
