# Generated by Django 5.2.15 on 2026-07-29 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0100_courserunenrollment_edx_enrollment_retry_count"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partnerschool",
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="PartnerSchoolProgram",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.TextField(
                        blank=True,
                        help_text="Recipient address for this program. Leave blank to use the school's default email.",
                    ),
                ),
                (
                    "alt_email",
                    models.TextField(
                        blank=True,
                        help_text="Alternative contact address, recorded for reference only. Learner records are NOT sent here.",
                    ),
                ),
                (
                    "partner_school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_links",
                        to="courses.partnerschool",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_school_links",
                        to="courses.program",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partnerschool",
            name="programs",
            field=models.ManyToManyField(
                blank=True,
                help_text="Programs this school accepts records for. Learners only see schools assigned to the program whose record they are sharing.",
                related_name="partner_schools",
                through="courses.PartnerSchoolProgram",
                to="courses.program",
            ),
        ),
        migrations.AddIndex(
            model_name="partnerschoolprogram",
            index=models.Index(
                fields=["program", "partner_school"],
                name="courses_par_program_e97557_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="partnerschoolprogram",
            constraint=models.UniqueConstraint(
                fields=("partner_school", "program", "email"),
                name="partner_school_program_email_unique",
            ),
        ),
    ]
