# Generated by Django 5.2.15 on 2026-08-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0102_backfill_verified_course_enrollments"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificates_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If set, no certificates will be generated for this course, even if a live certificate page exists.",
            ),
        ),
        migrations.AddField(
            model_name="program",
            name="certificates_disabled",
            field=models.BooleanField(
                default=False,
                help_text="If set, no certificates will be generated for this program, even if a live certificate page exists.",
            ),
        ),
    ]
