# Generated by Django 5.2.15 on 2026-09-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0027_discountcontractattachmentredemption_email_message_id_and_more"),
        ("courses", "0103_gate_certificate_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserunenrollment",
            name="b2b_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="course_run_enrollments",
                to="b2b.contractpage",
            ),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="b2b_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="program_enrollments",
                to="b2b.contractpage",
            ),
        ),
    ]
