# Generated by Django 5.2.15 on 2026-08-31 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0027_discountcontractattachmentredemption_email_message_id_and_more"),
        ("courses", "0103_gate_certificate_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="courserun",
            name="b2b_contracts",
            field=models.ManyToManyField(
                related_name="course_runs", to="b2b.contractpage"
            ),
        ),
        migrations.AddField(
            model_name="courserun",
            name="b2b_only",
            field=models.BooleanField(
                default=False, help_text="Indicates if the course run is B2B only"
            ),
        ),
        migrations.AlterField(
            model_name="courserun",
            name="b2b_contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="b2b.contractpage",
            ),
        ),
    ]
