# Generated by Django 5.2.15 on 2026-09-09 20:36

from django.db import migrations
from django.db.models import F


def populate_enrollment_contracts(apps, schema_editor):
    """
    Backfill the b2b_contract field that's been added to CourseRunEnrollment and
    ProgramEnrollment.
    """

    CourseRunEnrollment = apps.get_model("courses", "CourseRunEnrollment")
    CourseRunEnrollment.objects.filter(run__b2b_contract__isnull=False).update(
        b2b_contract_id=F("run__b2b_contract__id")
    )

    # Course run enrollments are easy since we only allow (now) a run to belong
    # to a contract or not. Programs can belong to any number of contracts so it's
    # a bit more tricky. So I think, for each program that has an association with
    # a contract, find the users who are enrolled in the program and see what
    # runs they're enrolled in that count for the program. If the runs are B2B,
    # then we can update the program enrollment accordingly.

    ProgramEnrollment = apps.get_model("courses", "ProgramEnrollment")
    ProgramEnrollment.objects.filter()


def reverse_noop(apps, schema_editor):
    """Do nothing - won't be able to determine who touched the enrollment contract field last."""


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0104_add_enrollment_contract_fks"),
    ]

    operations = [migrations.RunPython(populate_enrollment_contracts, reverse_noop)]
