# Generated by Django 5.2.15 on 2026-08-31 17:07

from django.db import migrations


def backfill_b2b_contract_associations(apps, schema_editor):
    """Backfill the many-to-many with values from b2b_contract."""

    CourseRun = apps.get_model("courses", "CourseRun")

    runs = (
        CourseRun.all_objects.prefetch_related("b2b_contract")
        .filter(b2b_contract__isnull=False)
        .all()
    )

    for run in runs:
        run.b2b_contracts.add(run.b2b_contract)


def reverse_backfill(apps, schema_editor):
    """
    Reverse the backfill.

    If the run has b2b_contractS but not the old b2b_contract, then backfill
    the first one into b2b_contract. Otherwise, leave it alone.
    """

    CourseRun = apps.get_model("courses", "CourseRun")

    eligible_runs = (
        CourseRun.all_objects.prefetch_related("b2b_contracts")
        .filter(b2b_contract__isnull=True, b2b_contracts__isnull=False)
        .all()
    )

    for run in eligible_runs:
        run.b2b_contract = run.b2b_contracts.first()
        run.save()


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0104_add_multi_contract_fks"),
    ]

    operations = [
        migrations.RunPython(
            code=backfill_b2b_contract_associations, reverse_code=reverse_backfill
        ),
    ]
