# Generated by Django 5.2.15 on 2026-09-09 20:36

from django.db import migrations


def populate_enrollment_contracts(apps, schema_editor):
    """
    Backfill the b2b_contract field that's been added to CourseRunEnrollment and
    ProgramEnrollment.
    """

    CourseRunEnrollment = apps.get_model("courses", "CourseRunEnrollment")
    contract_course_run_enrollments = CourseRunEnrollment.objects.filter(run__b2b_contract__isnull=False).all()

    for enrollment in contract_course_run_enrollments:
        # We haven't dropped the b2b_contract FK as of yet, so use that to determine
        # the ownership for the enrollment.
        enrollment.b2b_contract = enrollment.run.b2b_contract
        enrollment.save()

    # Program backfill works differently. The program may be associated with one
    # or more contracts. So, each enrollment may be for a different contract, or
    # it may not be a B2B enrollment at all (if the program isn't flagged b2b_only).
    # Loop through and see what 

    ProgramEnrollment = apps.get_model("courses", "ProgramEnrollment")

    # Using objects here and not all_objects - want to avoid enrollments that might
    # be for no longer valid contracts; if the user re-enrolls in the program,
    # that will cause the enrollment to be linked up to the correct contract.
    contract_program_enrollments = ProgramEnrollment.objects.filter(program__b2b_contracts__isnull=False).all()
    updated_enrollments = []

    for enrollment in contract_program_enrollments:
        user = enrollment.user
        first_user_contract = user.b2b_contracts.filter(id__in=list(enrollment.program.b2b_contracts.values_list("id", flat=True))).first()

        if not first_user_contract and enrollment.program.b2b_only:
            msg = f"Enrollment for {user} in {enrollment.program} seems invalid - program is marked B2B-only but the user isn't in the contract."
            raise ValueError(msg)

        if not first_user_contract:
            continue

        enrollment.b2b_contract = first_user_contract
        updated_enrollments.append(enrollment)

    if len(updated_enrollments) > 0:
        ProgramEnrollment.objects.bulk_update(updated_enrollments, ["b2b_contract"])


def reverse_noop(apps, schema_editor):
    """Do nothing - won't be able to determine who touched the enrollment contract field last."""


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0107_add_enrollment_contract_fks"),
    ]

    operations = [migrations.RunPython(populate_enrollment_contracts, reverse_noop)]
