# Generated by Django 5.2.17 on 2026-09-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0108_backfill_enrollment_contracts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courserun",
            name="variant_industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Original"),
                    ("E", "Energy"),
                    ("F", "Finance"),
                    ("HC", "Healthcare"),
                    ("M", "Manufacturing"),
                ],
                db_index=True,
                default="",
                help_text="Variant: Describes the industry the run is adapted for.",
                max_length=3,
            ),
        ),
    ]
