# Generated by Django 5.2.17 on 2026-10-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0109_add_manufacturing_variant"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="programrequirement",
            name="courses_programrequirement_node_check",
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="track",
            field=models.ForeignKey(
                blank=True,
                help_text="The track the learner chose, a track node of this program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="courses.programrequirement",
            ),
        ),
        migrations.AddField(
            model_name="programrequirement",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="programrequirement",
            name="node_type",
            field=models.CharField(
                choices=[
                    ("program_root", "Program Root"),
                    ("operator", "Operator"),
                    ("course", "Course"),
                    ("program", "Program"),
                    ("track", "Track"),
                ],
                max_length=12,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="programrequirement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("course__isnull", True),
                        ("depth", 1),
                        ("node_type", "program_root"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                        ("required_program__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("depth__gt", 1),
                        ("node_type", "operator"),
                        ("operator__isnull", False),
                        ("required_program__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", False),
                        ("depth__gt", 1),
                        ("node_type", "course"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                        ("required_program__isnull", True),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("depth__gt", 1),
                        ("node_type", "program"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                        ("required_program__isnull", False),
                    ),
                    models.Q(
                        ("course__isnull", True),
                        ("depth", 3),
                        ("node_type", "track"),
                        ("operator__isnull", True),
                        ("operator_value__isnull", True),
                        ("required_program__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="courses_programrequirement_node_check",
            ),
        ),
    ]
