"""Constants for the B2B app."""

ORG_INDEX_SLUG = "organizations"

CONTRACT_INTEGRATION_SSO = "sso"
CONTRACT_INTEGRATION_SSO_NAME = "SSO"
CONTRACT_INTEGRATION_NONSSO = "non-sso"
CONTRACT_INTEGRATION_NONSSO_NAME = "Non-SSO"

CONTRACT_INTEGRATION_CHOICES = zip(
    [CONTRACT_INTEGRATION_SSO, CONTRACT_INTEGRATION_NONSSO],
    [CONTRACT_INTEGRATION_SSO_NAME, CONTRACT_INTEGRATION_NONSSO_NAME],
)

B2B_RUN_TAG_FORMAT = "{year}_C{contract_id}"

ORG_KEY_MAX_LENGTH = 30
