"""Constants for the B2B app."""

ORG_INDEX_SLUG = "organizations"

CONTRACT_MEMBERSHIP_MANAGED = "managed"
CONTRACT_MEMBERSHIP_MANAGED_NAME = "Managed"
CONTRACT_MEMBERSHIP_CODE = "code"
CONTRACT_MEMBERSHIP_CODE_NAME = "Enrollment Code"
CONTRACT_MEMBERSHIP_AUTO = "auto"
CONTRACT_MEMBERSHIP_AUTO_NAME = "Auto Enrollment"

CONTRACT_MEMBERSHIP_AUTOS = [
    CONTRACT_MEMBERSHIP_AUTO,
    CONTRACT_MEMBERSHIP_MANAGED,
]

CONTRACT_MEMBERSHIP_TYPE_CHOICES = list(
    zip(
        [
            CONTRACT_MEMBERSHIP_MANAGED,
            CONTRACT_MEMBERSHIP_CODE,
            CONTRACT_MEMBERSHIP_AUTO,
        ],
        [
            CONTRACT_MEMBERSHIP_MANAGED_NAME,
            CONTRACT_MEMBERSHIP_CODE_NAME,
            CONTRACT_MEMBERSHIP_AUTO_NAME,
        ],
    )
)

B2B_RUN_TAG_FORMAT = "{run_idx}T{contract_id}C{year}"

ORG_KEY_MAX_LENGTH = 30
