"""Constants for the B2B app."""

ORG_INDEX_SLUG = "organizations"

# Old values which will be removed in a future PR
CONTRACT_MEMBERSHIP_SSO = "sso"
CONTRACT_MEMBERSHIP_SSO_NAME = "SSO"
CONTRACT_MEMBERSHIP_NONSSO = "non-sso"
CONTRACT_MEMBERSHIP_NONSSO_NAME = "Non-SSO"
# New values
CONTRACT_MEMBERSHIP_MANAGED = "managed"
CONTRACT_MEMBERSHIP_MANAGED_NAME = "Managed"
CONTRACT_MEMBERSHIP_CODE = "code"
CONTRACT_MEMBERSHIP_CODE_NAME = "Enrollment Code"
CONTRACT_MEMBERSHIP_AUTO = "auto"
CONTRACT_MEMBERSHIP_AUTO_NAME = "Auto Enrollment"

CONTRACT_MEMBERSHIP_AUTOS = [
    CONTRACT_MEMBERSHIP_AUTO,
    CONTRACT_MEMBERSHIP_MANAGED,
    CONTRACT_MEMBERSHIP_SSO,
]

CONTRACT_MEMBERSHIP_CHOICES = zip(
    [
        CONTRACT_MEMBERSHIP_SSO,
        CONTRACT_MEMBERSHIP_NONSSO,
        CONTRACT_MEMBERSHIP_MANAGED,
        CONTRACT_MEMBERSHIP_CODE,
        CONTRACT_MEMBERSHIP_AUTO,
    ],
    [
        CONTRACT_MEMBERSHIP_SSO_NAME,
        CONTRACT_MEMBERSHIP_NONSSO_NAME,
        CONTRACT_MEMBERSHIP_MANAGED_NAME,
        CONTRACT_MEMBERSHIP_CODE_NAME,
        CONTRACT_MEMBERSHIP_AUTO_NAME,
    ],
)
# When the integration_type field is removed, this should be removed as well.
# It is just here so we can have the same choices in both integration_type and
# membership_type fields. (Using the constant for `choices` consumes it.)
CONTRACT_MEMBERSHIP_TYPE_CHOICES = zip(
    [
        CONTRACT_MEMBERSHIP_SSO,
        CONTRACT_MEMBERSHIP_NONSSO,
        CONTRACT_MEMBERSHIP_MANAGED,
        CONTRACT_MEMBERSHIP_CODE,
        CONTRACT_MEMBERSHIP_AUTO,
    ],
    [
        CONTRACT_MEMBERSHIP_SSO_NAME,
        CONTRACT_MEMBERSHIP_NONSSO_NAME,
        CONTRACT_MEMBERSHIP_MANAGED_NAME,
        CONTRACT_MEMBERSHIP_CODE_NAME,
        CONTRACT_MEMBERSHIP_AUTO_NAME,
    ],
)

B2B_RUN_TAG_FORMAT = "{year}_C{contract_id}"

ORG_KEY_MAX_LENGTH = 30
