# generated by datamodel-codegen:
#   filename:  https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml
#   version:   0.66.0
#   command:   datamodel-codegen --input openapi.yaml --output-model-type dataclasses.dataclass --preset standard-py312-20260619 --output b2b/keycloak_admin_dataclasses.py --url https://www.keycloak.org/docs-api/latest/rest-api/openapi.yaml --enable-version-header --enable-command-header

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

from typing_extensions import deprecated


@dataclass
class Access:
    roles: list[str] | None = None
    verify_caller: bool | None = None


@dataclass
class AuthDetailsRepresentation:
    realmId: str | None = None
    clientId: str | None = None
    userId: str | None = None
    ipAddress: str | None = None


@dataclass
class AuthenticationExecutionExportRepresentation:
    authenticatorConfig: str | None = None
    authenticator: str | None = None
    authenticatorFlow: bool | None = None
    requirement: str | None = None
    priority: int | None = None
    autheticatorFlow: bool | None = None
    flowAlias: str | None = None
    userSetupAllowed: bool | None = None


@dataclass
class AuthenticationExecutionInfoRepresentation:
    id: str | None = None
    requirement: str | None = None
    displayName: str | None = None
    alias: str | None = None
    description: str | None = None
    requirementChoices: list[str] | None = None
    configurable: bool | None = None
    authenticationFlow: bool | None = None
    providerId: str | None = None
    authenticationConfig: str | None = None
    flowId: str | None = None
    level: int | None = None
    index: int | None = None
    priority: int | None = None


@dataclass
class AuthenticationExecutionRepresentation:
    authenticatorConfig: str | None = None
    authenticator: str | None = None
    authenticatorFlow: bool | None = None
    requirement: str | None = None
    priority: int | None = None
    autheticatorFlow: bool | None = None
    id: str | None = None
    flowId: str | None = None
    parentFlow: str | None = None


@dataclass
class AuthenticationFlowRepresentation:
    id: str | None = None
    alias: str | None = None
    description: str | None = None
    providerId: str | None = None
    topLevel: bool | None = None
    builtIn: bool | None = None
    authenticationExecutions: (
        list[AuthenticationExecutionExportRepresentation] | None
    ) = None


@dataclass
class AuthenticatorConfigRepresentation:
    id: str | None = None
    alias: str | None = None
    config: dict[str, str] | None = None


@dataclass
class AuthorizationDetailsJSONRepresentation:
    type: str | None = None
    locations: list[str] | None = None
    actions: list[str] | None = None
    datatypes: list[str] | None = None
    identifier: str | None = None
    privileges: list[str] | None = None
    customData: dict[str, Any] | None = None


class BruteForceStrategy(StrEnum):
    LINEAR = 'LINEAR'
    MULTIPLE = 'MULTIPLE'


@dataclass
class CertificateRepresentation:
    privateKey: str | None = None
    publicKey: str | None = None
    certificate: str | None = None
    kid: str | None = None
    jwks: str | None = None


@dataclass
class ClaimRepresentation:
    name: bool | None = None
    username: bool | None = None
    profile: bool | None = None
    picture: bool | None = None
    website: bool | None = None
    email: bool | None = None
    gender: bool | None = None
    locale: bool | None = None
    address: bool | None = None
    phone: bool | None = None


@dataclass
class ClientInitialAccessCreatePresentation:
    expiration: int | None = None
    count: int | None = None
    webOrigins: list[str] | None = None


@dataclass
class ClientInitialAccessPresentation:
    id: str | None = None
    token: str | None = None
    timestamp: int | None = None
    expiration: int | None = None
    count: int | None = None
    remainingCount: int | None = None


@dataclass
class ClientPolicyConditionRepresentation:
    condition: str | None = None
    configuration: dict[str, Any] | None = None


@dataclass
class ClientPolicyExecutorRepresentation:
    executor: str | None = None
    configuration: dict[str, Any] | None = None


@dataclass
class ClientPolicyRepresentation:
    name: str | None = None
    description: str | None = None
    enabled: bool | None = None
    conditions: list[ClientPolicyConditionRepresentation] | None = None
    profiles: list[str] | None = None


@dataclass
class ClientProfileRepresentation:
    name: str | None = None
    description: str | None = None
    executors: list[ClientPolicyExecutorRepresentation] | None = None


@dataclass
class ClientProfilesRepresentation:
    profiles: list[ClientProfileRepresentation] | None = None
    globalProfiles: list[ClientProfileRepresentation] | None = None


@dataclass
class Composites:
    realm: list[str] | None = None
    client: dict[str, list[str]] | None = None
    application: dict[str, list[str]] | None = None


@dataclass
class ConfigPropertyRepresentation:
    name: str | None = None
    label: str | None = None
    helpText: str | None = None
    type: str | None = None
    defaultValue: Any | None = None
    options: list[str] | None = None
    secret: bool | None = None
    required: bool | None = None
    readOnly: bool | None = None


@dataclass
class Confirmation:
    x5t_S256: str | None = None
    jkt: str | None = None


class DecisionEffect(StrEnum):
    PERMIT = 'PERMIT'
    DENY = 'DENY'


class DecisionStrategy(StrEnum):
    AFFIRMATIVE = 'AFFIRMATIVE'
    UNANIMOUS = 'UNANIMOUS'
    CONSENSUS = 'CONSENSUS'


@dataclass
class ErrorRepresentation:
    field: str | None = None
    errorMessage: str | None = None
    params: list[Any] | None = None
    errors: list[ErrorRepresentation] | None = None


@dataclass
class EventRepresentation:
    id: str | None = None
    time: int | None = None
    type: str | None = None
    realmId: str | None = None
    clientId: str | None = None
    userId: str | None = None
    sessionId: str | None = None
    ipAddress: str | None = None
    error: str | None = None
    details: dict[str, str] | None = None


@dataclass
class FederatedIdentityRepresentation:
    identityProvider: str | None = None
    userId: str | None = None
    userName: str | None = None


@dataclass
class GlobalRequestResult:
    successRequests: list[str] | None = None
    failedRequests: list[str] | None = None


@dataclass
class GroupRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    path: str | None = None
    parentId: str | None = None
    subGroupCount: int | None = None
    subGroups: list[GroupRepresentation] | None = None
    attributes: dict[str, list[str]] | None = None
    realmRoles: list[str] | None = None
    clientRoles: dict[str, list[str]] | None = None
    access: dict[str, bool] | None = None


@dataclass
class IDToken:
    jti: str | None = None
    exp: int | None = None
    nbf: int | None = None
    iat: int | None = None
    iss: str | None = None
    sub: str | None = None
    typ: str | None = None
    azp: str | None = None
    otherClaims: dict[str, Any] | None = None
    nonce: str | None = None
    auth_time: int | None = None
    sid: str | None = None
    at_hash: str | None = None
    c_hash: str | None = None
    name: str | None = None
    given_name: str | None = None
    family_name: str | None = None
    middle_name: str | None = None
    nickname: str | None = None
    preferred_username: str | None = None
    profile: str | None = None
    picture: str | None = None
    website: str | None = None
    email: str | None = None
    email_verified: bool | None = None
    gender: str | None = None
    birthdate: str | None = None
    zoneinfo: str | None = None
    locale: str | None = None
    phone_number: str | None = None
    phone_number_verified: bool | None = None
    updated_at: int | None = None
    claims_locales: str | None = None
    acr: str | None = None
    s_hash: str | None = None


@dataclass
class IdentityProviderMapperRepresentation:
    id: str | None = None
    name: str | None = None
    identityProviderAlias: str | None = None
    identityProviderMapper: str | None = None
    config: dict[str, str] | None = None


@dataclass
class IdentityProviderMapperTypeRepresentation:
    id: str | None = None
    name: str | None = None
    category: str | None = None
    helpText: str | None = None
    properties: list[ConfigPropertyRepresentation] | None = None


@dataclass
class IdentityProviderRepresentation:
    alias: str | None = None
    displayName: str | None = None
    internalId: str | None = None
    providerId: str | None = None
    enabled: bool | None = None
    updateProfileFirstLoginMode: str | None = None
    trustEmail: bool | None = None
    storeToken: bool | None = None
    addReadTokenRoleOnCreate: bool | None = None
    authenticateByDefault: bool | None = None
    linkOnly: bool | None = None
    hideOnLogin: bool | None = None
    firstBrokerLoginFlowAlias: str | None = None
    postBrokerLoginFlowAlias: str | None = None
    organizationId: str | None = None
    config: dict[str, str] | None = None
    types: list[str] | None = None
    updateProfileFirstLogin: bool | None = None


@dataclass
class KeyStoreConfig:
    realmCertificate: bool | None = None
    storePassword: str | None = None
    keyPassword: str | None = None
    keyAlias: str | None = None
    realmAlias: str | None = None
    format: str | None = None
    keySize: int | None = None
    validity: int | None = None


class KeyUse(StrEnum):
    SIG = 'SIG'
    ENC = 'ENC'
    JWT_SVID = 'JWT_SVID'


class Logic(StrEnum):
    POSITIVE = 'POSITIVE'
    NEGATIVE = 'NEGATIVE'


@dataclass
class ManagementPermissionReference:
    enabled: bool | None = None
    resource: str | None = None
    scopePermissions: dict[str, str] | None = None


class MembershipType(StrEnum):
    UNMANAGED = 'UNMANAGED'
    MANAGED = 'MANAGED'


@dataclass
class OrganizationDomainRepresentation:
    name: str | None = None
    verified: bool | None = None


@dataclass
class Permission:
    rsid: str | None = None
    rsname: str | None = None
    scopes: list[str] | None = None
    claims: dict[str, list[str]] | None = None


class PolicyEnforcementMode(StrEnum):
    ENFORCING = 'ENFORCING'
    PERMISSIVE = 'PERMISSIVE'
    DISABLED = 'DISABLED'


@dataclass
class PolicyProviderRepresentation:
    type: str | None = None
    name: str | None = None
    group: str | None = None
    description: str | None = None
    code: str | None = None


@dataclass
class PropertyConfig:
    applicable: bool | None = None
    value: Any | None = None


@dataclass
class ProtocolMapperEvaluationRepresentation:
    mapperId: str | None = None
    mapperName: str | None = None
    containerId: str | None = None
    containerName: str | None = None
    containerType: str | None = None
    protocolMapper: str | None = None


@dataclass
class ProtocolMapperRepresentation:
    id: str | None = None
    name: str | None = None
    protocol: str | None = None
    protocolMapper: str | None = None
    consentRequired: bool | None = None
    consentText: str | None = None
    config: dict[str, str] | None = None


@dataclass
class PublishedRealmRepresentation:
    realm: str | None = None
    public_key: str | None = None
    token_service: str | None = None
    account_service: str | None = None
    tokens_not_before: int | None = None


@dataclass
class RealmEventsConfigRepresentation:
    eventsEnabled: bool | None = None
    eventsExpiration: int | None = None
    eventsListeners: list[str] | None = None
    enabledEventTypes: list[str] | None = None
    adminEventsEnabled: bool | None = None
    adminEventsDetailsEnabled: bool | None = None


@dataclass
class RequiredActionConfigInfoRepresentation:
    properties: list[ConfigPropertyRepresentation] | None = None


@dataclass
class RequiredActionConfigRepresentation:
    config: dict[str, str] | None = None


@dataclass
class RequiredActionProviderRepresentation:
    alias: str | None = None
    name: str | None = None
    providerId: str | None = None
    enabled: bool | None = None
    defaultAction: bool | None = None
    priority: int | None = None
    config: dict[str, str] | None = None


@dataclass
class ResourceOwnerRepresentation:
    id: str | None = None
    name: str | None = None


@dataclass
class ResourceType:
    type: str | None = None
    scopes: list[str] | None = None
    scopeAliases: dict[str, list[str]] | None = None
    groupType: str | None = None


@dataclass
class RoleRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    scopeParamRequired: bool | None = None
    composite: bool | None = None
    composites: Composites | None = None
    clientRole: bool | None = None
    containerId: str | None = None
    attributes: dict[str, list[str]] | None = None


@dataclass
class RolesRepresentation:
    realm: list[RoleRepresentation] | None = None
    client: dict[str, list[RoleRepresentation]] | None = None
    application: dict[str, list[RoleRepresentation]] | None = None


@dataclass
class ScopeMappingRepresentation:
    self: str | None = None
    client: str | None = None
    clientTemplate: str | None = None
    clientScope: str | None = None
    roles: list[str] | None = None


@dataclass
class SocialLinkRepresentation:
    socialProvider: str | None = None
    socialUserId: str | None = None
    socialUsername: str | None = None


class Status(StrEnum):
    PENDING = 'PENDING'
    EXPIRED = 'EXPIRED'


class StepExecutionStatus(StrEnum):
    COMPLETED = 'COMPLETED'
    PENDING = 'PENDING'


@dataclass
class UPAttributePermissions:
    view: list[str] | None = None
    edit: list[str] | None = None


@dataclass
class UPAttributeRequired:
    roles: list[str] | None = None
    scopes: list[str] | None = None


@dataclass
class UPAttributeSelector:
    scopes: list[str] | None = None


@dataclass
class UPGroup:
    name: str | None = None
    displayHeader: str | None = None
    displayDescription: str | None = None
    annotations: dict[str, Any] | None = None


class UnmanagedAttributePolicy(StrEnum):
    ENABLED = 'ENABLED'
    ADMIN_VIEW = 'ADMIN_VIEW'
    ADMIN_EDIT = 'ADMIN_EDIT'


@dataclass
class UserConsentRepresentation:
    clientId: str | None = None
    grantedClientScopes: list[str] | None = None
    createdDate: int | None = None
    lastUpdatedDate: int | None = None
    grantedRealmRoles: list[str] | None = None


@dataclass
class UserFederationMapperRepresentation:
    id: str | None = None
    name: str | None = None
    federationProviderDisplayName: str | None = None
    federationMapperType: str | None = None
    config: dict[str, str] | None = None


@dataclass
class UserFederationProviderRepresentation:
    id: str | None = None
    displayName: str | None = None
    providerName: str | None = None
    config: dict[str, str] | None = None
    priority: int | None = None
    fullSyncPeriod: int | None = None
    changedSyncPeriod: int | None = None
    lastSync: int | None = None


@dataclass
class UserProfileAttributeGroupMetadata:
    name: str | None = None
    displayHeader: str | None = None
    displayDescription: str | None = None
    annotations: dict[str, Any] | None = None


@dataclass
class UserProfileAttributeMetadata:
    name: str | None = None
    displayName: str | None = None
    required: bool | None = None
    readOnly: bool | None = None
    annotations: dict[str, Any] | None = None
    validators: dict[str, dict[str, Any]] | None = None
    group: str | None = None
    multivalued: bool | None = None
    defaultValue: str | None = None


@dataclass
class UserProfileMetadata:
    attributes: list[UserProfileAttributeMetadata] | None = None
    groups: list[UserProfileAttributeGroupMetadata] | None = None


@dataclass
class UserSessionRepresentation:
    id: str | None = None
    username: str | None = None
    userId: str | None = None
    ipAddress: str | None = None
    start: int | None = None
    lastAccess: int | None = None
    rememberMe: bool | None = None
    clients: dict[str, str] | None = None
    transientUser: bool | None = None


@dataclass
class WorkflowConcurrencyRepresentation:
    cancel_in_progress: str | None = None
    restart_in_progress: str | None = None


@dataclass
class WorkflowScheduleRepresentation:
    after: str | None = None
    batch_size: int | None = None


@dataclass
class WorkflowStateRepresentation:
    errors: list[str] | None = None


@dataclass
class WorkflowStepRepresentation:
    uses: str | None = None
    after: str | None = None
    scheduled_at: int | None = None
    status: StepExecutionStatus | None = None
    id: str | None = None
    config: dict[str, list[str]] | None = None


@dataclass
class AdminEventRepresentation:
    id: str | None = None
    time: int | None = None
    realmId: str | None = None
    authDetails: AuthDetailsRepresentation | None = None
    operationType: str | None = None
    resourceType: str | None = None
    resourcePath: str | None = None
    representation: str | None = None
    error: str | None = None
    details: dict[str, str] | None = None


@dataclass
class AuthenticatorConfigInfoRepresentation:
    name: str | None = None
    providerId: str | None = None
    helpText: str | None = None
    properties: list[ConfigPropertyRepresentation] | None = None


@dataclass
class Authorization:
    permissions: list[Permission] | None = None


@dataclass
class AuthorizationSchema:
    resourceTypes: dict[str, ResourceType] | None = None


@dataclass
class ClientMappingsRepresentation:
    id: str | None = None
    client: str | None = None
    mappings: list[RoleRepresentation] | None = None


@dataclass
class ClientPoliciesRepresentation:
    policies: list[ClientPolicyRepresentation] | None = None
    globalPolicies: list[ClientPolicyRepresentation] | None = None


@dataclass
class ClientScopeRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    protocol: str | None = None
    attributes: dict[str, str] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None


@deprecated('ClientTemplateRepresentation is deprecated.')
@dataclass
class ClientTemplateRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    protocol: str | None = None
    fullScopeAllowed: bool | None = None
    bearerOnly: bool | None = None
    consentRequired: bool | None = None
    standardFlowEnabled: bool | None = None
    implicitFlowEnabled: bool | None = None
    directAccessGrantsEnabled: bool | None = None
    serviceAccountsEnabled: bool | None = None
    publicClient: bool | None = None
    frontchannelLogout: bool | None = None
    attributes: dict[str, str] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None


@dataclass
class ClientTypeRepresentation:
    name: str | None = None
    provider: str | None = None
    parent: str | None = None
    config: dict[str, PropertyConfig] | None = None


@dataclass
class ClientTypesRepresentation:
    client_types: list[ClientTypeRepresentation] | None = None
    global_client_types: list[ClientTypeRepresentation] | None = None


@dataclass
class ComponentRepresentation:
    id: str | None = None
    name: str | None = None
    providerId: str | None = None
    providerType: str | None = None
    parentId: str | None = None
    subType: str | None = None
    config: dict[str, list[str]] | None = None


@dataclass
class ComponentTypeRepresentation:
    id: str | None = None
    helpText: str | None = None
    properties: list[ConfigPropertyRepresentation] | None = None
    clientProperties: list[ConfigPropertyRepresentation] | None = None
    metadata: dict[str, Any] | None = None


@dataclass
class CredentialRepresentation:
    id: str | None = None
    type: str | None = None
    userLabel: str | None = None
    createdDate: int | None = None
    secretData: str | None = None
    credentialData: str | None = None
    priority: int | None = None
    value: str | None = None
    temporary: bool | None = None
    device: str | None = None
    hashedSaltedValue: str | None = None
    salt: str | None = None
    hashIterations: int | None = None
    counter: int | None = None
    algorithm: str | None = None
    digits: int | None = None
    period: int | None = None
    config: dict[str, list[str]] | None = None
    federationLink: str | None = None


@dataclass
class KeyMetadataRepresentation:
    providerId: str | None = None
    providerPriority: int | None = None
    kid: str | None = None
    status: str | None = None
    type: str | None = None
    algorithm: str | None = None
    publicKey: str | None = None
    certificate: str | None = None
    use: KeyUse | None = None
    validTo: int | None = None


@dataclass
class KeysMetadataRepresentation:
    active: dict[str, str] | None = None
    keys: list[KeyMetadataRepresentation] | None = None


@dataclass
class MappingsRepresentation:
    realmMappings: list[RoleRepresentation] | None = None
    clientMappings: dict[str, ClientMappingsRepresentation] | None = None


@dataclass
class MemberRepresentation:
    id: str | None = None
    username: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    email: str | None = None
    emailVerified: bool | None = None
    attributes: dict[str, list[str]] | None = None
    userProfileMetadata: UserProfileMetadata | None = None
    enabled: bool | None = None
    self: str | None = None
    origin: str | None = None
    createdTimestamp: int | None = None
    totp: bool | None = None
    federationLink: str | None = None
    serviceAccountClientId: str | None = None
    credentials: list[CredentialRepresentation] | None = None
    disableableCredentialTypes: list[str] | None = None
    requiredActions: list[str] | None = None
    federatedIdentities: list[FederatedIdentityRepresentation] | None = None
    realmRoles: list[str] | None = None
    clientRoles: dict[str, list[str]] | None = None
    clientConsents: list[UserConsentRepresentation] | None = None
    notBefore: int | None = None
    applicationRoles: dict[str, list[str]] | None = None
    socialLinks: list[SocialLinkRepresentation] | None = None
    groups: list[str] | None = None
    access: dict[str, bool] | None = None
    membershipType: MembershipType | None = None


@dataclass
class OrganizationInvitationRepresentation:
    id: str | None = None
    organizationId: str | None = None
    email: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    sentDate: int | None = None
    expiresAt: int | None = None
    status: Status | None = None
    inviteLink: str | None = None


@dataclass
class OrganizationRepresentation:
    id: str | None = None
    name: str | None = None
    alias: str | None = None
    enabled: bool | None = None
    description: str | None = None
    redirectUrl: str | None = None
    attributes: dict[str, list[str]] | None = None
    domains: list[OrganizationDomainRepresentation] | None = None
    members: list[MemberRepresentation] | None = None
    identityProviders: list[IdentityProviderRepresentation] | None = None
    groups: list[GroupRepresentation] | None = None


@dataclass
class UPAttribute:
    name: str | None = None
    displayName: str | None = None
    validations: dict[str, dict[str, Any]] | None = None
    annotations: dict[str, Any] | None = None
    required: UPAttributeRequired | None = None
    permissions: UPAttributePermissions | None = None
    selector: UPAttributeSelector | None = None
    group: str | None = None
    multivalued: bool | None = None
    defaultValue: str | None = None


@dataclass
class UPConfig:
    attributes: list[UPAttribute] | None = None
    groups: list[UPGroup] | None = None
    unmanagedAttributePolicy: UnmanagedAttributePolicy | None = None


@dataclass
class UserRepresentation:
    id: str | None = None
    username: str | None = None
    firstName: str | None = None
    lastName: str | None = None
    email: str | None = None
    emailVerified: bool | None = None
    attributes: dict[str, list[str]] | None = None
    userProfileMetadata: UserProfileMetadata | None = None
    enabled: bool | None = None
    self: str | None = None
    origin: str | None = None
    createdTimestamp: int | None = None
    totp: bool | None = None
    federationLink: str | None = None
    serviceAccountClientId: str | None = None
    credentials: list[CredentialRepresentation] | None = None
    disableableCredentialTypes: list[str] | None = None
    requiredActions: list[str] | None = None
    federatedIdentities: list[FederatedIdentityRepresentation] | None = None
    realmRoles: list[str] | None = None
    clientRoles: dict[str, list[str]] | None = None
    clientConsents: list[UserConsentRepresentation] | None = None
    notBefore: int | None = None
    applicationRoles: dict[str, list[str]] | None = None
    socialLinks: list[SocialLinkRepresentation] | None = None
    groups: list[str] | None = None
    access: dict[str, bool] | None = None


@dataclass
class WorkflowRepresentation:
    id: str | None = None
    name: str | None = None
    enabled: bool | None = None
    on: str | None = None
    schedule: WorkflowScheduleRepresentation | None = None
    concurrency: WorkflowConcurrencyRepresentation | None = None
    if_: str | None = None
    steps: list[WorkflowStepRepresentation] | None = None
    state: WorkflowStateRepresentation | None = None
    with_: dict[str, list[str]] | None = None
    cancelInProgress: str | None = None
    restartInProgress: str | None = None


@dataclass
class AccessToken:
    jti: str | None = None
    exp: int | None = None
    nbf: int | None = None
    iat: int | None = None
    iss: str | None = None
    sub: str | None = None
    typ: str | None = None
    azp: str | None = None
    otherClaims: dict[str, Any] | None = None
    nonce: str | None = None
    auth_time: int | None = None
    sid: str | None = None
    at_hash: str | None = None
    c_hash: str | None = None
    name: str | None = None
    given_name: str | None = None
    family_name: str | None = None
    middle_name: str | None = None
    nickname: str | None = None
    preferred_username: str | None = None
    profile: str | None = None
    picture: str | None = None
    website: str | None = None
    email: str | None = None
    email_verified: bool | None = None
    gender: str | None = None
    birthdate: str | None = None
    zoneinfo: str | None = None
    locale: str | None = None
    phone_number: str | None = None
    phone_number_verified: bool | None = None
    updated_at: int | None = None
    claims_locales: str | None = None
    acr: str | None = None
    s_hash: str | None = None
    trusted_certs: list[str] | None = None
    allowed_origins: list[str] | None = None
    realm_access: Access | None = None
    resource_access: dict[str, Access] | None = None
    authorization: Authorization | None = None
    cnf: Confirmation | None = None
    scope: str | None = None
    authorization_details: list[AuthorizationDetailsJSONRepresentation] | None = None


@dataclass
class AbstractPolicyRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    type: str | None = None
    policies: list[str] | None = None
    resources: list[str] | None = None
    scopes: list[str] | None = None
    logic: Logic | None = None
    decisionStrategy: DecisionStrategy | None = None
    owner: str | None = None
    resourceType: str | None = None
    resourcesData: list[ResourceRepresentation] | None = None
    scopesData: list[ScopeRepresentation] | None = None


@deprecated('ApplicationRepresentation is deprecated.')
@dataclass
class ApplicationRepresentation:
    id: str | None = None
    clientId: str | None = None
    description: str | None = None
    type: str | None = None
    rootUrl: str | None = None
    adminUrl: str | None = None
    baseUrl: str | None = None
    surrogateAuthRequired: bool | None = None
    enabled: bool | None = None
    alwaysDisplayInConsole: bool | None = None
    clientAuthenticatorType: str | None = None
    secret: str | None = None
    registrationAccessToken: str | None = None
    defaultRoles: list[str] | None = None
    redirectUris: list[str] | None = None
    webOrigins: list[str] | None = None
    notBefore: int | None = None
    bearerOnly: bool | None = None
    consentRequired: bool | None = None
    standardFlowEnabled: bool | None = None
    implicitFlowEnabled: bool | None = None
    directAccessGrantsEnabled: bool | None = None
    serviceAccountsEnabled: bool | None = None
    authorizationServicesEnabled: bool | None = None
    directGrantsOnly: bool | None = None
    publicClient: bool | None = None
    frontchannelLogout: bool | None = None
    protocol: str | None = None
    attributes: dict[str, str] | None = None
    authenticationFlowBindingOverrides: dict[str, str] | None = None
    fullScopeAllowed: bool | None = None
    nodeReRegistrationTimeout: int | None = None
    registeredNodes: dict[str, int] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None
    clientTemplate: str | None = None
    useTemplateConfig: bool | None = None
    useTemplateScope: bool | None = None
    useTemplateMappers: bool | None = None
    defaultClientScopes: list[str] | None = None
    optionalClientScopes: list[str] | None = None
    authorizationSettings: ResourceServerRepresentation | None = None
    access: dict[str, bool] | None = None
    origin: str | None = None
    name: str | None = None
    claims: ClaimRepresentation | None = None


@dataclass
class ClientRepresentation:
    id: str | None = None
    clientId: str | None = None
    name: str | None = None
    description: str | None = None
    type: str | None = None
    rootUrl: str | None = None
    adminUrl: str | None = None
    baseUrl: str | None = None
    surrogateAuthRequired: bool | None = None
    enabled: bool | None = None
    alwaysDisplayInConsole: bool | None = None
    clientAuthenticatorType: str | None = None
    secret: str | None = None
    registrationAccessToken: str | None = None
    defaultRoles: list[str] | None = None
    redirectUris: list[str] | None = None
    webOrigins: list[str] | None = None
    notBefore: int | None = None
    bearerOnly: bool | None = None
    consentRequired: bool | None = None
    standardFlowEnabled: bool | None = None
    implicitFlowEnabled: bool | None = None
    directAccessGrantsEnabled: bool | None = None
    serviceAccountsEnabled: bool | None = None
    authorizationServicesEnabled: bool | None = None
    directGrantsOnly: bool | None = None
    publicClient: bool | None = None
    frontchannelLogout: bool | None = None
    protocol: str | None = None
    attributes: dict[str, str] | None = None
    authenticationFlowBindingOverrides: dict[str, str] | None = None
    fullScopeAllowed: bool | None = None
    nodeReRegistrationTimeout: int | None = None
    registeredNodes: dict[str, int] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None
    clientTemplate: str | None = None
    useTemplateConfig: bool | None = None
    useTemplateScope: bool | None = None
    useTemplateMappers: bool | None = None
    defaultClientScopes: list[str] | None = None
    optionalClientScopes: list[str] | None = None
    authorizationSettings: ResourceServerRepresentation | None = None
    access: dict[str, bool] | None = None
    origin: str | None = None


@dataclass
class ComponentExportRepresentation:
    id: str | None = None
    name: str | None = None
    providerId: str | None = None
    subType: str | None = None
    subComponents: dict[str, list[ComponentExportRepresentation]] | None = None
    config: dict[str, list[str]] | None = None


@dataclass
class EvaluationResultRepresentation:
    resource: ResourceRepresentation | None = None
    scopes: list[ScopeRepresentation] | None = None
    policies: list[PolicyResultRepresentation] | None = None
    status: DecisionEffect | None = None
    allowedScopes: list[ScopeRepresentation] | None = None
    deniedScopes: list[ScopeRepresentation] | None = None


@deprecated('OAuthClientRepresentation is deprecated.')
@dataclass
class OAuthClientRepresentation:
    id: str | None = None
    clientId: str | None = None
    description: str | None = None
    type: str | None = None
    rootUrl: str | None = None
    adminUrl: str | None = None
    baseUrl: str | None = None
    surrogateAuthRequired: bool | None = None
    enabled: bool | None = None
    alwaysDisplayInConsole: bool | None = None
    clientAuthenticatorType: str | None = None
    secret: str | None = None
    registrationAccessToken: str | None = None
    defaultRoles: list[str] | None = None
    redirectUris: list[str] | None = None
    webOrigins: list[str] | None = None
    notBefore: int | None = None
    bearerOnly: bool | None = None
    consentRequired: bool | None = None
    standardFlowEnabled: bool | None = None
    implicitFlowEnabled: bool | None = None
    directAccessGrantsEnabled: bool | None = None
    serviceAccountsEnabled: bool | None = None
    authorizationServicesEnabled: bool | None = None
    directGrantsOnly: bool | None = None
    publicClient: bool | None = None
    frontchannelLogout: bool | None = None
    protocol: str | None = None
    attributes: dict[str, str] | None = None
    authenticationFlowBindingOverrides: dict[str, str] | None = None
    fullScopeAllowed: bool | None = None
    nodeReRegistrationTimeout: int | None = None
    registeredNodes: dict[str, int] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None
    clientTemplate: str | None = None
    useTemplateConfig: bool | None = None
    useTemplateScope: bool | None = None
    useTemplateMappers: bool | None = None
    defaultClientScopes: list[str] | None = None
    optionalClientScopes: list[str] | None = None
    authorizationSettings: ResourceServerRepresentation | None = None
    access: dict[str, bool] | None = None
    origin: str | None = None
    name: str | None = None
    claims: ClaimRepresentation | None = None


@dataclass
class PolicyEvaluationRequest:
    context: dict[str, dict[str, str]] | None = None
    resources: list[ResourceRepresentation] | None = None
    resourceType: str | None = None
    clientId: str | None = None
    userId: str | None = None
    roleIds: list[str] | None = None
    entitlements: bool | None = None


@dataclass
class PolicyEvaluationResponse:
    results: list[EvaluationResultRepresentation] | None = None
    entitlements: bool | None = None
    status: DecisionEffect | None = None
    rpt: AccessToken | None = None


@dataclass
class PolicyRepresentation:
    id: str | None = None
    name: str | None = None
    description: str | None = None
    type: str | None = None
    policies: list[str] | None = None
    resources: list[str] | None = None
    scopes: list[str] | None = None
    logic: Logic | None = None
    decisionStrategy: DecisionStrategy | None = None
    owner: str | None = None
    resourceType: str | None = None
    resourcesData: list[ResourceRepresentation] | None = None
    scopesData: list[ScopeRepresentation] | None = None
    config: dict[str, str] | None = None


@dataclass
class PolicyResultRepresentation:
    policy: PolicyRepresentation | None = None
    status: DecisionEffect | None = None
    associatedPolicies: list[PolicyResultRepresentation] | None = None
    scopes: list[str] | None = None
    resourceType: str | None = None


@dataclass
class RealmRepresentation:
    id: str | None = None
    realm: str | None = None
    displayName: str | None = None
    displayNameHtml: str | None = None
    notBefore: int | None = None
    defaultSignatureAlgorithm: str | None = None
    revokeRefreshToken: bool | None = None
    refreshTokenMaxReuse: int | None = None
    accessTokenLifespan: int | None = None
    accessTokenLifespanForImplicitFlow: int | None = None
    ssoSessionIdleTimeout: int | None = None
    ssoSessionMaxLifespan: int | None = None
    ssoSessionIdleTimeoutRememberMe: int | None = None
    ssoSessionMaxLifespanRememberMe: int | None = None
    offlineSessionIdleTimeout: int | None = None
    offlineSessionMaxLifespanEnabled: bool | None = None
    offlineSessionMaxLifespan: int | None = None
    clientSessionIdleTimeout: int | None = None
    clientSessionMaxLifespan: int | None = None
    clientOfflineSessionIdleTimeout: int | None = None
    clientOfflineSessionMaxLifespan: int | None = None
    accessCodeLifespan: int | None = None
    accessCodeLifespanUserAction: int | None = None
    accessCodeLifespanLogin: int | None = None
    actionTokenGeneratedByAdminLifespan: int | None = None
    actionTokenGeneratedByUserLifespan: int | None = None
    oauth2DeviceCodeLifespan: int | None = None
    oauth2DevicePollingInterval: int | None = None
    enabled: bool | None = None
    sslRequired: str | None = None
    passwordCredentialGrantAllowed: bool | None = None
    registrationAllowed: bool | None = None
    registrationEmailAsUsername: bool | None = None
    rememberMe: bool | None = None
    verifyEmail: bool | None = None
    loginWithEmailAllowed: bool | None = None
    duplicateEmailsAllowed: bool | None = None
    resetPasswordAllowed: bool | None = None
    editUsernameAllowed: bool | None = None
    userCacheEnabled: bool | None = None
    realmCacheEnabled: bool | None = None
    bruteForceProtected: bool | None = None
    permanentLockout: bool | None = None
    maxTemporaryLockouts: int | None = None
    bruteForceStrategy: BruteForceStrategy | None = None
    maxFailureWaitSeconds: int | None = None
    minimumQuickLoginWaitSeconds: int | None = None
    waitIncrementSeconds: int | None = None
    quickLoginCheckMilliSeconds: int | None = None
    maxDeltaTimeSeconds: int | None = None
    failureFactor: int | None = None
    maxSecondaryAuthFailures: int | None = None
    privateKey: str | None = None
    publicKey: str | None = None
    certificate: str | None = None
    codeSecret: str | None = None
    roles: RolesRepresentation | None = None
    groups: list[GroupRepresentation] | None = None
    defaultRoles: list[str] | None = None
    defaultRole: RoleRepresentation | None = None
    adminPermissionsClient: ClientRepresentation | None = None
    defaultGroups: list[str] | None = None
    requiredCredentials: list[str] | None = None
    passwordPolicy: str | None = None
    otpPolicyType: str | None = None
    otpPolicyAlgorithm: str | None = None
    otpPolicyInitialCounter: int | None = None
    otpPolicyDigits: int | None = None
    otpPolicyLookAheadWindow: int | None = None
    otpPolicyPeriod: int | None = None
    otpPolicyCodeReusable: bool | None = None
    otpSupportedApplications: list[str] | None = None
    localizationTexts: dict[str, dict[str, str]] | None = None
    webAuthnPolicyRpEntityName: str | None = None
    webAuthnPolicySignatureAlgorithms: list[str] | None = None
    webAuthnPolicyRpId: str | None = None
    webAuthnPolicyAttestationConveyancePreference: str | None = None
    webAuthnPolicyAuthenticatorAttachment: str | None = None
    webAuthnPolicyRequireResidentKey: str | None = None
    webAuthnPolicyUserVerificationRequirement: str | None = None
    webAuthnPolicyCreateTimeout: int | None = None
    webAuthnPolicyAvoidSameAuthenticatorRegister: bool | None = None
    webAuthnPolicyAcceptableAaguids: list[str] | None = None
    webAuthnPolicyExtraOrigins: list[str] | None = None
    webAuthnPolicyPasswordlessRpEntityName: str | None = None
    webAuthnPolicyPasswordlessSignatureAlgorithms: list[str] | None = None
    webAuthnPolicyPasswordlessRpId: str | None = None
    webAuthnPolicyPasswordlessAttestationConveyancePreference: str | None = None
    webAuthnPolicyPasswordlessAuthenticatorAttachment: str | None = None
    webAuthnPolicyPasswordlessRequireResidentKey: str | None = None
    webAuthnPolicyPasswordlessUserVerificationRequirement: str | None = None
    webAuthnPolicyPasswordlessCreateTimeout: int | None = None
    webAuthnPolicyPasswordlessAvoidSameAuthenticatorRegister: bool | None = None
    webAuthnPolicyPasswordlessAcceptableAaguids: list[str] | None = None
    webAuthnPolicyPasswordlessExtraOrigins: list[str] | None = None
    webAuthnPolicyPasswordlessPasskeysEnabled: bool | None = None
    clientProfiles: ClientProfilesRepresentation | None = None
    clientPolicies: ClientPoliciesRepresentation | None = None
    users: list[UserRepresentation] | None = None
    federatedUsers: list[UserRepresentation] | None = None
    scopeMappings: list[ScopeMappingRepresentation] | None = None
    clientScopeMappings: dict[str, list[ScopeMappingRepresentation]] | None = None
    clients: list[ClientRepresentation] | None = None
    clientScopes: list[ClientScopeRepresentation] | None = None
    defaultDefaultClientScopes: list[str] | None = None
    defaultOptionalClientScopes: list[str] | None = None
    browserSecurityHeaders: dict[str, str] | None = None
    smtpServer: dict[str, str] | None = None
    userFederationProviders: list[UserFederationProviderRepresentation] | None = None
    userFederationMappers: list[UserFederationMapperRepresentation] | None = None
    loginTheme: str | None = None
    accountTheme: str | None = None
    adminTheme: str | None = None
    emailTheme: str | None = None
    eventsEnabled: bool | None = None
    eventsExpiration: int | None = None
    eventsListeners: list[str] | None = None
    enabledEventTypes: list[str] | None = None
    adminEventsEnabled: bool | None = None
    adminEventsDetailsEnabled: bool | None = None
    identityProviders: list[IdentityProviderRepresentation] | None = None
    identityProviderMappers: list[IdentityProviderMapperRepresentation] | None = None
    protocolMappers: list[ProtocolMapperRepresentation] | None = None
    components: dict[str, list[ComponentExportRepresentation]] | None = None
    internationalizationEnabled: bool | None = None
    supportedLocales: list[str] | None = None
    defaultLocale: str | None = None
    authenticationFlows: list[AuthenticationFlowRepresentation] | None = None
    authenticatorConfig: list[AuthenticatorConfigRepresentation] | None = None
    requiredActions: list[RequiredActionProviderRepresentation] | None = None
    browserFlow: str | None = None
    registrationFlow: str | None = None
    directGrantFlow: str | None = None
    resetCredentialsFlow: str | None = None
    clientAuthenticationFlow: str | None = None
    dockerAuthenticationFlow: str | None = None
    firstBrokerLoginFlow: str | None = None
    attributes: dict[str, str] | None = None
    keycloakVersion: str | None = None
    userManagedAccessAllowed: bool | None = None
    organizationsEnabled: bool | None = None
    organizations: list[OrganizationRepresentation] | None = None
    verifiableCredentialsEnabled: bool | None = None
    adminPermissionsEnabled: bool | None = None
    social: bool | None = None
    updateProfileOnInitialSocialLogin: bool | None = None
    socialProviders: dict[str, str] | None = None
    applicationScopeMappings: dict[str, list[ScopeMappingRepresentation]] | None = None
    applications: list[ApplicationRepresentation] | None = None
    oauthClients: list[OAuthClientRepresentation] | None = None
    clientTemplates: list[ClientTemplateRepresentation] | None = None
    scimApiEnabled: bool | None = None


@dataclass
class ResourceRepresentation:
    field_id: str | None = None
    name: str | None = None
    uris: list[str] | None = None
    type: str | None = None
    scopes: list[ScopeRepresentation] | None = None
    icon_uri: str | None = None
    owner: ResourceOwnerRepresentation | None = None
    ownerManagedAccess: bool | None = None
    displayName: str | None = None
    attributes: dict[str, list[str]] | None = None
    uri: str | None = None
    scopesUma: list[ScopeRepresentation] | None = None


@dataclass
class ResourceServerRepresentation:
    id: str | None = None
    clientId: str | None = None
    name: str | None = None
    allowRemoteResourceManagement: bool | None = None
    policyEnforcementMode: PolicyEnforcementMode | None = None
    resources: list[ResourceRepresentation] | None = None
    policies: list[PolicyRepresentation] | None = None
    scopes: list[ScopeRepresentation] | None = None
    decisionStrategy: DecisionStrategy | None = None
    authorizationSchema: AuthorizationSchema | None = None


@dataclass
class ScopeRepresentation:
    id: str | None = None
    name: str | None = None
    iconUri: str | None = None
    policies: list[PolicyRepresentation] | None = None
    resources: list[ResourceRepresentation] | None = None
    displayName: str | None = None
