# Generated by Django 2.1.7 on 2019-03-22 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openedx", "0001_add_oauth_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenEdxUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[("edx", "edx")], default="edx", max_length=20
                    ),
                ),
                (
                    "has_been_synced",
                    models.BooleanField(
                        default=True,
                        help_text="Indicates whether a corresponding user has been created on the openedx platform",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="openedxuser", unique_together={("user", "platform")}
        ),
    ]
