# Generated by Django 4.2.20 on 2025-04-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "openedx",
            "0006_rename_openedxapiauth_user_access_token_expires_on_openedx_ope_user_id_76f6b9_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openedxuser",
            name="edx_username",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
