# Generated by Django 4.2.20 on 2025-04-08 19:40

import logging

from django.db import migrations
from django.db.models import OuterRef, Subquery

log = logging.getLogger(__name__)


def populate_edx_username(apps, schema_editor):
    OpenEdxUser = apps.get_model("openedx", "OpenEdxUser")
    User = apps.get_model("users", "User")

    edx_users_missing_username = OpenEdxUser.objects.filter(
        id__in=OpenEdxUser.objects.filter(edx_username__isnull=True).only("id")[:5000]
    )

    while num_updates := edx_users_missing_username.update(
        edx_username=Subquery(
            User.objects.filter(id=OuterRef("user_id")).values("username")[:1]
        ),
    ):
        log.info("Updated %s edx usernames", num_updates)


class Migration(migrations.Migration):
    # ensure we don't lock records
    atomic = False

    dependencies = [
        ("openedx", "0007_add_edx_username"),
    ]

    operations = [
        migrations.RunPython(populate_edx_username, migrations.RunPython.noop)
    ]
