# Generated by Django 4.2.22 on 2025-08-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx", "0008_populate_edx_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="openedxuser",
            name="desired_edx_username",
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
