# Generated by Django 4.2.22 on 2025-08-21 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx", "0009_add_desired_edx_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openedxuser",
            name="desired_edx_username",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
