# Generated by Django 4.2.22 on 2025-08-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openedx", "0010_drop_unique_on_desired_edx_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="openedxuser",
            name="has_sync_error",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether we hit an error or not trying to sync the user",
            ),
        ),
        migrations.AddField(
            model_name="openedxuser",
            name="sync_error_data",
            field=models.JSONField(
                default=None, help_text="The JSON sync error from openedx", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="openedxuser",
            index=models.Index(
                fields=["has_been_synced", "has_sync_error"], name="sync_state_idx"
            ),
        ),
    ]
