# Generated by Django 5.2.15 on 2026-09-14 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0106_drop_courserun_b2b_contract_constraints"),
        ("openedx", "0011_add_sync_error_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRunClone",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("source_courseware_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("cloning", "Cloning"),
                            ("cloned", "Cloned"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                (
                    "clone_requested_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Stamped just before edX is asked to clone. A retry that finds the target already in edX treats it as ours only when this is set.",
                        null=True,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                (
                    "course_run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edx_clone",
                        to="courses.courserun",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
