upstreams:
  - id: 1
    nodes:
      "nginx:8013": 1
    type: roundrobin

global_rules:
routes:
  - id: 1
    name: "app-wildcard"
    desc: "General route for the application, includes user data if any."
    priority: 0
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile ol-profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout/oidc"
        post_logout_redirect_uri: ${{APP_LOGOUT_URL}}
        unauth_action: "pass"
      response-rewrite:
        headers:
          set:
            Content-Security-Policy: frame-ancestors 'self' ${{OPENEDX_API_BASE_URL}}
    uris:
      - "/*"
  - id: 2
    name: "app-login"
    desc: "Establish a session for the user."
    priority: 10
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile ol-profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout/oidc"
        post_logout_redirect_uri: ${{APP_LOGOUT_URL}}
        unauth_action: "auth"
      redirect:
        uri: "/dashboard"
      response-rewrite:
        headers:
          set:
            Content-Security-Policy: frame-ancestors 'self' ${{OPENEDX_API_BASE_URL}}
    uris:
      - "/login"
      - "/login/"
      - "/admin/login*"


#END
