upstreams:
  - id: 1
    nodes:
      "nginx:8013": 1
    type: roundrobin

routes:
  - id: 1
    name: "app-wildcard"
    desc: "General route for the application, includes user data if any."
    priority: 0
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile ol-profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{APP_LOGOUT_URL}}
        unauth_action: "pass"
    uris:
      - "/*"
  - id: 2
    name: "app-login"
    desc: "Establish a session for the user."
    priority: 10
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile ol-profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{APP_LOGOUT_URL}}
        unauth_action: "auth"
      redirect:
        uri: "/dashboard"
    uris:
      - "/login*"
  - id: 3
    name: "logout-redirect"
    desc: "Strip trailing slash from logout redirect."
    priority: 10
    upstream_id: 1
    uri: "/logout/*"
    plugins:
      redirect:
        uri: "/logout"

#END