# Generated by Django 3.2.12 on 2022-04-12 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CountryIncomeThreshold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("country_code", models.CharField(max_length=2, unique=True)),
                ("income_threshold", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CurrencyExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("currency_code", models.CharField(max_length=3)),
                ("exchange_rate", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FlexiblePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("auto-approved", "auto-approved"),
                            ("created", "created"),
                            ("docs-sent", "docs-sent"),
                            ("pending-docs", "pending-docs"),
                            ("pending-manual-approval", "pending-manual-approval"),
                            ("skipped", "skipped"),
                            ("reset", "reset"),
                        ],
                        default="created",
                        max_length=30,
                    ),
                ),
                ("income_usd", models.FloatField(null=True)),
                ("original_income", models.FloatField(null=True)),
                ("original_currency", models.CharField(max_length=10, null=True)),
                ("country_of_income", models.CharField(max_length=100, null=True)),
                ("date_exchange_rate", models.DateTimeField(null=True)),
                ("date_documents_sent", models.DateField(blank=True, null=True)),
                ("justification", models.TextField(null=True)),
                ("country_of_residence", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
