# Generated by Django 3.2.12 on 2022-04-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0001_initial_flex_pricing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="exchange_rate",
            field=models.FloatField(
                help_text="Indexed to USD at the time the record was created."
            ),
        ),
    ]
