# Generated by Django 3.2.12 on 2022-04-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0002_update_exchange_rate_field_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="currency_code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="exchange_rate",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Indexed to USD at the time the record was created.",
                max_digits=4,
            ),
        ),
    ]
