# Generated by Django 3.2.12 on 2022-04-29 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flexiblepricing", "0005_add_flexible_pricing_request_form"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flexiblepricingrequestform",
            name="from_address",
        ),
        migrations.RemoveField(
            model_name="flexiblepricingrequestform",
            name="subject",
        ),
        migrations.RemoveField(
            model_name="flexiblepricingrequestform",
            name="to_address",
        ),
    ]
