# Generated by Django 3.2.12 on 2022-05-06 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0009_flexiblepricingrequestform_more_textboxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="flexibleprice",
            name="cms_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="flexiblepricing.flexiblepricingrequestsubmission",
            ),
        ),
    ]
