# Generated by Django 3.2.12 on 2022-05-09 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flexiblepricing", "0011_add_flexible_pricing_request_form"),
    ]

    operations = [
        migrations.AddField(
            model_name="currencyexchangerate",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
