# Generated by Django 3.2.13 on 2022-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0013_add_flex_price_fk_to_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currencyexchangerate",
            name="exchange_rate",
            field=models.FloatField(),
        ),
    ]
