# Generated by Django 3.2.14 on 2022-08-02 19:06

from django.db import migrations


def update_skipped_flexpricings_to_denied(apps, schema_editor):
    """Changes existing 'skipped' FlexiblePricing objects into 'denied'."""

    FlexiblePrice = apps.get_model("flexiblepricing", "FlexiblePrice")

    FlexiblePrice.objects.filter(status="skipped").update(status="denied")


def update_denied_flexpricings_to_skipped(apps, schema_editor):
    """Does the opposite of update_skipped_flexpricings_to_denied."""

    FlexiblePrice = apps.get_model("flexiblepricing", "FlexiblePrice")

    FlexiblePrice.objects.filter(status="denied").update(status="skipped")


class Migration(migrations.Migration):

    dependencies = [
        ("flexiblepricing", "0016_allow_blank_country_of_residence"),
    ]

    operations = [
        migrations.RunPython(
            update_skipped_flexpricings_to_denied, update_denied_flexpricings_to_skipped
        )
    ]
