# Generated by Django 3.2.14 on 2022-08-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0017_update_flexible_pricing_rename_skipped_to_denied"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flexibleprice",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "approved"),
                    ("auto-approved", "auto-approved"),
                    ("created", "created"),
                    ("pending-manual-approval", "pending-manual-approval"),
                    ("denied", "denied"),
                    ("reset", "reset"),
                ],
                default="created",
                max_length=30,
            ),
        ),
    ]
