# Generated by Django 3.2.14 on 2022-08-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flexiblepricing", "0018_alter_flexibleprice_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="flexibleprice",
            constraint=models.UniqueConstraint(
                fields=("user", "courseware_content_type", "courseware_object_id"),
                name="unique_user_courseware_object",
            ),
        ),
    ]
