# Generated by Django 3.2.18 on 2023-05-08 16:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexiblepricing', '0020_alter_flexibleprice_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexiblepricingrequestsubmission',
            name='form_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
