# Generated by Django 3.2.14 on 2022-08-08 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flexiblepricing", "0018_alter_flexibleprice_status"),
        ("micromasters_import", "0001_micromasters_pk_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramTierId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "micromasters_tier_program_id",
                    models.IntegerField(
                        help_text="The primary key of Tier Program in MicroMasters",
                        unique=True,
                    ),
                ),
                (
                    "flexible_price_tier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flexiblepricing.flexiblepricetier",
                    ),
                ),
            ],
        ),
    ]
