# Generated by Django 3.2.15 on 2022-10-12 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0020_courseruncertificate_certificate_page_revision"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("micromasters_import", "0002_programtiers_pk_mapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCertificateRevisionId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_page_revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.pagerevision",
                    ),
                ),
                (
                    "course",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
            ],
        ),
    ]
