# Generated by Django 3.2.15 on 2022-12-07 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0024_add_record_share_model"),
        ("wagtailcore", "0066_collection_management_permissions"),
        ("micromasters_import", "0003_course_certificate_id_mapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="programid",
            name="program_certificate_revision",
            field=models.ForeignKey(
                blank=True,
                help_text="Program certificate page revision ID in MITxOnline (Used for importing program certificates)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.revision",
            ),
        ),
        migrations.AlterField(
            model_name="programid",
            name="micromasters_id",
            field=models.IntegerField(
                help_text="The primary key of the program in MicroMasters", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="programid",
            name="program",
            field=models.OneToOneField(
                help_text="The primary key of the program in MITxOnline",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.program",
            ),
        ),
    ]
